### ISSUE TITLE
[Bug Report] Dialog - broke in 2.2

### ISSUE THREAD

**Issue by GautierDele** [vuetifyjs/vuetify#10536]
### Environment
**Vuetify Version:** 2.2.11
**Last working version:** 2.1.0
**Vue Version:** 2.6.11
**Browsers:** Chrome 80.0.3987.87
**OS:** Windows 10

### Steps to reproduce
Click on the dialog button and the second dialog isn't appearing

### Expected Behavior
There should be a second button in order to open a second dialog

### Actual Behavior
No button given

### Reproduction Link
<a href="https://codepen.io/gautierdele/pen/GRJJEJL" target="_blank">https://codepen.io/gautierdele/pen/GRJJEJL</a>

### Other comments
It also seems in my application that event propagation is no longer stopped... When I click in the dialog it trigger the parent

**Comment by GautierDele** [comment]
I just tested in 2.1.18 and it seems to be working. So I guess it's a 2.2 modification but I can't find in the releases the point talking about it ...

**Comment by MajesticPotatoe** [comment]
works in 2.2.8
likely related to #10522

**Comment by jacekkarczmarczyk** [comment]
Fixed in https://github.com/vuetifyjs/vuetify/commit/cc17fe19751826d950ca5207749699935d227020

**Comment by GautierDele** [comment]
Effectively the tuesday's realease did fix one of the problem but i'm still getting the problem that the events seems to propagate through dialog.
On my app if I click on a dialog it triggers the parent @click event even if it's not visible since the dialog is fullscreen.

As you can see in this codepen: https://codepen.io/gautierdele/pen/GRJJEJL
When we click anywhere in the fullscreen dialog it actually triggers the event as it used not to (downgrade the package to 2.1.18 in the settings and you will see it wont)

Gautier

**Comment by KaelWD** [comment]
That's intentional: #10167

**Comment by GautierDele** [comment]
Ok i did not know, mooving the event to the content element fixed the problem.

Thanks
