### ISSUE TITLE
[Bug Report] Vuetify v-parallax issue

### ISSUE THREAD

**Issue by marabino20** [vuetifyjs/vuetify#10640]
### Environment
**Vuetify Version:** 2.2.12
**Vue Version:** 3.12.0
**Browsers:** Chrome 80.0.3987.116
**OS:** Mac OS 10.13.6

### Steps to reproduce
Only try to put a v-parallax inside the v-container thar is in a v-sheet because im try to use the v-app-bar the example title is "Prominent w/ scroll shrink and image, fading on scroll", so this example have the content inside a v-sheet and the code ```<v-sheet id="scrolling-techniques-3" class="overflow-y-auto" :max-height="getWindowsWidht()">```, that class "overflow-y-auto is required to the v-app-bar to work.

So when i put a v-parallax inside then container that is inside the v-sheet, this one do not work.

### Expected Behavior
i'm working with Prominent w/ scroll shrink and image, fading on scroll, and try to put inside of the v-sheet an v-parallax and this last one do not work

### Actual Behavior
i'm working with Prominent w/ scroll shrink and image, fading on scroll, and try to put inside of the v-sheet an v-parallax and this last one do not work

### Reproduction Link
<a href="https://codepen.io/marabino20/pen/MWwjxLM" target="_blank">https://codepen.io/marabino20/pen/MWwjxLM</a>

### Other comments
When i remove the class "overflow-y-auto" from the v-sheet the v-parallax works but the v-app-bar fails

Thanks

**Comment by rsaleri** [comment]
Didn't understand the issue, but this codepen at least compiles: https://codepen.io/rsaleri/pen/RwPpgVw

**Comment by marabino20** [comment]
Yes, thanks @rsaleri for the help, the reproduction is already working better. The issue can be seen in the middle of the example, the v-parallax does not work but if you remove the class  "overflow-y-auto" from the v-sheet, the app bar and stop working but the v-parallax works well.


https://codepen.io/marabino20/pen/MWwjxLM

**Comment by johnleider** [comment]
You need to drastically reduce the amount of code to reproduce this issue.

**Comment by marabino20** [comment]
> You need to drastically reduce the amount of code to reproduce this issue.

Done.

**Comment by Leespiker** [comment]
@marabino20 The problem is still unclear. Can you reproduce the issue in less than 20 lines of code?

**Comment by johnleider** [comment]
This Issue is being closed due to inactivity.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com/).
