### ISSUE TITLE
[Bug Report] Display bug with outlined select when in small container and value selected

### ISSUE THREAD

**Issue by ligne13** [vuetifyjs/vuetify#10711]
### Environment
**Vuetify Version:** 2.2.15
**Vue Version:** 2.6.11
**Browsers:** Chrome 80.0.3987.122
**OS:** Mac OS 10.15.3

### Steps to reproduce
Put a v-select in a narrow container, and select a value.

### Expected Behavior
The v-select height should stay the same

### Actual Behavior
The v-select height is too high (the input element is wrapped on another line below)

### Reproduction Link
<a href="https://codepen.io/ligne13/pen/JjdJNMb?editors=1010" target="_blank">https://codepen.io/ligne13/pen/JjdJNMb?editors=1010</a>

**Comment by johnleider** [comment]
I tested this on Mojave Chrome 80 and see nothing out of the ordinary. Need additional information.

**Comment by jacekkarczmarczyk** [comment]
https://codepen.io/jkarczm/pen/abOGPeZ?editors=1000

**Comment by ligne13** [comment]
Hi @johnleider 
On the pen I created (https://codepen.io/ligne13/pen/JjdJNMb?editors=1010), try to size down your window under 1904px. You will see the v-select too high:
![image](https://user-images.githubusercontent.com/81624/76888211-d3b3c580-6883-11ea-856f-54ffee80c13f.png)

**Comment by johnleider** [comment]
fixed with 254bb29a3

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Comment by ligne13** [comment]
Hi,

the issue still exists, after updating to Vuetify 2.2.32: https://codepen.io/ligne13/pen/JjdJNMb?editors=1010
![image](https://user-images.githubusercontent.com/81624/83970378-bc5e0480-a8d5-11ea-826f-972ee1aa2350.png)

**Comment by ligne13** [comment]
Hi, the issue still exists after updating to 2.2.32: https://codepen.io/ligne13/pen/JjdJNMb?editors=1010.
![image](https://user-images.githubusercontent.com/81624/83970548-8705e680-a8d6-11ea-8775-6fe25c061676.png)
