### ISSUE TITLE
inheritAttrs is false make v-text-field can't use vee-validate

### ISSUE THREAD

**Issue by CasperLaiTW** [vuetifyjs/vuetify#1072]
### Steps to reproduce
Get error in console.

```
"[Vue warn]: Error in directive validate bind hook: 'Error: [vee-validate] Cannot add a listener for non-existent field undefined.'
```

### Versions

Vue: 2.4.1
Vuetify: 0.4.15
vee-validate: 2.0.0-rc.7

### What is expected ?

name or another props (eg: data-vv-name) must be passing to component 

### What is actually happening ?

`inheritAttrs` is false, so default behavior was disabled.

### Reproduction Link

https://codepen.io/CasperLai/pen/pwMrMg

**Comment by johnleider** [comment]
Has vee-validate been updated to support Vue 2.4? That functionality (inheritAttrs) is crucial for that component to now have hundreds of custom defined props to account for all of the things you could put on a input(type="text")

**Comment by logaretm** [comment]
It seems its an issue on my end here with `vee-validate` because it depended on inherited attributes, I have fixed it in this [commit](https://github.com/baianat/vee-validate/commit/ead1df915ac67a05dd0378ea706c0cc242551af2)

**Comment by johnleider** [comment]
Would this be considered resolved then?

**Comment by CasperLaiTW** [comment]
Yes, look good :)
Thanks @logaretm and @johnleider

**Comment by lobosan** [comment]
Hi, is this fix available for vee-validate@2.0.0-rc.7 ?
because I'm not able to integrate it with vuetify@0.4.15

**Comment by CasperLaiTW** [comment]
Hi @lobosan I think didn't fix.

vee-validate did't release.

**Comment by iury** [comment]
you'll need to apply the patch manually until the next release. just download it in the master branch (https://github.com/baianat/vee-validate/tree/master/dist) and override the files in your project folder node_modules/vee-validate/dist

**Comment by rafaelramalho19** [comment]
@logaretm Any date planned on the release?

**Comment by logaretm** [comment]
@rafaelramalho19 within a couple of days max, sorry for the delay.
