### ISSUE TITLE
[Bug Report] materialdesignicons stopped working properly

### ISSUE THREAD

**Issue by seongjin605** [vuetifyjs/vuetify#10797]
### Environment
**Vue Version:** 2.6.11
**Nuxt Version**: 2.10.1
**@nuxtjs/vuetify Version**: 1.9.0
**Vuetify Version:** 2.2.8
**Browsers:** Chrome 80.0.3987.132
**OS:** Mac OS 10.15.3

--- 

### Expected Behavior
https://v1.vuetifyjs.com/en/components/paginations

--- 

### Actual Behavior Bug image
![image](https://user-images.githubusercontent.com/16683075/76269342-931ce080-62b4-11ea-8e8e-9affdc273c83.png)

**I did not modify the icon, but one day it suddenly changed to like this**
**Is this material icon's CDN problem?**

**Comment by seongjin605** [comment]
### Expected Behavior
https://vuetifyjs.com/en/components/ratings/

**The same problem occurs with the v-rating component.**

### Actual Behavior Bug image
![image](https://user-images.githubusercontent.com/16683075/76271571-450bdb00-62bc-11ea-8399-c0e401b2e0e6.png)

**Comment by ngongon** [comment]
This is happening from about 2 hours ago.

**Comment by MpEliaz** [comment]
same here!

**Comment by MajesticPotatoe** [comment]
Are you CDN without explicitly specifying a version?

**Comment by seongjin605** [comment]
@MajesticPotatoe yes, i just used @nuxtjs/vuetify Version: 1.9.0. 
Here are the material icon CDN links.(yourPath/node_modules/@nuxtjs/vuetify/dist/icon.js)

```javascript
const presetsCDN = {
    'mdi': 'https://cdn.jsdelivr.net/npm/@mdi/font@latest/css/materialdesignicons.min.css',
    'md': 'https://fonts.googleapis.com/css?family=Material+Icons',
    'fa': 'https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@latest/css/all.min.css',
    'fa4': 'https://cdn.jsdelivr.net/npm/font-awesome@4.7.0/css/font-awesome.min.css'
};
export default function setupIcons(preset) {
    this.options.head.link.push({
        rel: 'stylesheet',
        type: 'text/css',
        href: presetsCDN[preset]
    });
}
//# sourceMappingURL=icons.js.map
```

**Comment by ngongon** [comment]
<img width="73" alt="스크린샷 2020-03-10 오전 11 34 23" src="https://user-images.githubusercontent.com/26247535/76274207-50aed000-62c3-11ea-89e1-9a1ebed2b75c.png">
For more information, some default icons are having problems.
For example, arrow_down icon of autocomplete, list icon of left-toggle-drawer, arrow_down icon of list group.

**Comment by MajesticPotatoe** [comment]
@seongjin605 `@mdi/font@latest` you are not explicitly specifying a cdn version, this ultimately can cause cache issues when mdi updates their libraries.

**Comment by ngongon** [comment]
@seongjin605 Thanks, I urgently edited node_modules and redeployed.

**Comment by lukef** [comment]
I'm having the same issue. Not using the CDN version. Installed via npm (`"vuetify": "^2.1.0"`).

**Comment by ElijahKotyluk** [comment]
For Vuetify + Nuxt using create-nuxt-app, I ended up uninstalling `@nuxtjs/vuetify`, and installing the Vuetify package and specified `@mdi/font@4.9.95` and created a Vuetify plugin. All works perfectly again.

```js
// plugins/vuetify.js
import Vue from 'vue'
import Vuetify from 'vuetify'

import 'vuetify/dist/vuetify.min.css'
import '@mdi/font/css/materialdesignicons.css'
Vue.use(Vuetify)

export default (ctx) => {
  const vuetify = new Vuetify({
    theme: {
      dark: false
    }
  })
  ctx.app.vuetify = vuetify
  ctx.$vuetify = vuetify.framework
}

// nuxt.config.js
  ...
  plugins: ['~/plugins/commerce.js', '~plugins/vuetify.js'],
  ...
```

If this comment should not be here, just let me know and I will do so.

**Comment by PabloRN** [comment]
> @seongjin605 `@mdi/font@latest` you are not explicitly specifying a cdn version, this ultimately can cause cache issues when mdi updates their libraries.

Sorry not working with latest

**Comment by KaelWD** [comment]
> Sorry not working with latest

Yeah that's what he said. 

This is a problem with jsdelivr, it doesn't redirect `@latest` to the actual version. 

- Loads https://cdn.jsdelivr.net/npm/@mdi/font@latest/css/materialdesignicons.css
- Browser has v4.5.95 cached
- Loads `../fonts/materialdesignicons-webfont.eot?v=4.5.95`
- Cache miss, so it pulls in https://cdn.jsdelivr.net/npm/@mdi/font@latest/fonts/materialdesignicons-webfont.eot?v=4.5.95
- You now have the v4.5.95 stylesheet with v5.0.45 fonts, because the `?v=` is just for cache busting

http://unpkg.com/ doesn't have this problem because it redirects to the actual version, preventing a cache mismatch. If you use jsdelivr you must specify a full version number.

**Comment by kevinalexandersurjadi** [comment]
In my kind of environment
```
nuxt: 2.11.0
@nuxtjs/vuetify: 1.9.0
```
I was experiencing the same issue, but I solved it by installing extra devDependency of 
```
@mdi/font: 5.0.45
```
and add it to my vuetify config (vuetify.options.js) like this (refering to [https://vuetifyjs.com/en/customization/icons/#installing-iconfonts](url))
```
import '@mdi/font/css/materialdesignicons.css'

export default {
  icons: {
    iconfont: 'mdi'
  }
}
```
and I add it to nuxt.config.js like this
```
...
  buildModules: [
    '@nuxtjs/vuetify'
  ],
  vuetify: {
    optionsPath: './vuetify.options.js'
  }
...
```
hope this helps.

**Comment by Ed-ouard** [comment]
It seems that the issue has been fixed now, with the latest version of mdi fonts.
No need to change the package.

**Comment by PabloRN** [comment]
> It seems that the issue has been fixed now, with the latest version of mdi fonts.
> No need to change the package.

not really...

**Comment by PabloRN** [comment]
> * 4.5.95

Hey @KaelWD in my case I can see:
`https://cdn.jsdelivr.net/npm/@mdi/font@latest/fonts/materialdesignicons-webfont.woff2?v=5.0.45`
and still showing wrong icons

**Comment by liranh85** [comment]
Fixed for me, all icons are rendered correctly again. Thanks for the quick fix!

**Comment by hiiwave** [comment]
I encountered the same problem using vuetify installed via vue-cli.
Here is how I managed to solve it:

1. Search `materialdesignicons.min.css` in the project folder. It appears at `public/index.html`.
2. Modify it to …`materialdesignicons.css`.
3. Working now.

It appears that the minified version has the wrong version. Thus 
I switch to regular version instead temporarily. Hope that helps.

**Comment by KaelWD** [comment]
> It appears that the minified version has the old content in v4.9x

Because your browser has it cached. If you clear the cache or **specify a version range** it'll work again.

**Comment by hiiwave** [comment]
> specify a version range it'll work again.

How can I do this? I tried adding `?v=5` at the end of the url but it did not work.

**Comment by johnleider** [comment]
If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
