### ISSUE TITLE
[Documentation] Algolia search

### ISSUE THREAD

**Issue by Azaleet** [vuetifyjs/vuetify#10991]
### Environment

**Browsers:** Chrome 80.0.3987.149
**OS:** Windows 10

### Steps to reproduce
click search input and type v-checkbox.
then press enter

### Expected Behavior
but i know, that v-checkbox page exists:
https://vuetifyjs.com/en/components/selection-controls/

### Actual Behavior
Now u get nothing

### Reproduction Link
<a href="https://vuetifyjs.com/ru/components/selects/" target="_blank">https://vuetifyjs.com/ru/components/selects/</a>

**Comment by MajesticPotatoe** [comment]
This has been resolved. Thank you for the report. Please note it may take up to 24h for Algolia to re-crawl the website and the functionality to return. I will pin this post for the time being. Thank you for your patience.

**Comment by davidbludlow** [comment]
It can be argued that this was ever completely fixed. It is 5 days later and https://vuetifyjs.com/en/components/selection-controls/ still doesn't show up when you search for "v-checkbox"
![image](https://user-images.githubusercontent.com/5985136/78612762-c1e49300-782f-11ea-9338-3cf634e48646.png)

**Comment by MajesticPotatoe** [comment]
The actual underlying issue has in fact been solved (you actually got zero results all together after typing more than 2 letters, due to pre-rendering being broken). The content returned from a search however is a different issue all together. If you search a simple `checkbox` you will get the results you are looking for. Search results in general we lack some control over as its handled by a third party, and is depending on what they are able to crawl.

**Comment by davidbludlow** [comment]
That makes sense. Hopefully algolia gets better sometime in the future.
