### ISSUE TITLE
[Bug Report] Unable to mock $vuetify in unit tests

### ISSUE THREAD

**Issue by Bastczuak** [vuetifyjs/vuetify#11278]
### Environment
**Vuetify Version:** 2.2.11
**Vue Version:** 2.6.11
**Browsers:** Safari 13.1
**OS:** Mac OS 10.14.6

### Steps to reproduce
1. yarn
2. yarn test:unit
3. open file example.spec.js and see snapshot result.

### Expected Behavior
I want to mock instance variable `$vuetify.breakpoint.smAndDown` by providing a mock like described in the docu https://vuetifyjs.com/en/getting-started/unit-testing/ and https://vue-test-utils.vuejs.org/api/options.html#mocks. I installed Vuetify like described in a config file `setup.jest.js` and configured jest to use it.

I expected that in my test that mocked `smAndDown` is set to `true`.

### Actual Behavior
`$vuetify` instance variable is not mockable. The actual implementation is not overwritten by passing a mock object either to `new Vuetify()` nor to `shallowMount` or `mount`.

### Reproduction Link
<a href="https://github.com/Bastczuak/vuetify-mock-issue" target="_blank">https://github.com/Bastczuak/vuetify-mock-issue</a>

### Other comments
Please fix the issue creator! I was not able to create an issue in Chrome browser because after submitting a new issue I got redirected to my account email settings.

**Comment by benjamindedonder** [comment]
I am experiencing this issue as well. In my case I wish to mock $vuetify.goTo and test if it has been called.

Reproduction: https://github.com/benjamindedonder/vuetify-mock-issue

**Comment by johnleider** [comment]
Ugh, sorry about that. The mocking example is absolutely *not* correct. Admittedly I haven't tested in a regular Vue app in awhile and I'm not happy where our testing information is at. Unfortunately, we have extremely limited bandwidth at the moment. This is on our radar and something that is 100% going to be easier to support for v3.

Just to clarify, the reason this issue exists is because of how we support Typescript and has been around for awhile. I greatly appreciate your patience and any help is appreciated.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Comment by Bastczuak** [comment]
@johnleider I tried to understand what the problem is, but ufff, this project is so big and advanced, I'm not sure if I can help here.

**Comment by ElVisPL** [comment]
@johnleider is there any workaround?
I tried doing something similar to https://github.com/vuetifyjs/vuetify/commit/c90fc9d9aa5faaf5d0b24056374f8adcbf5781d5#diff-7a779ad127e9d0a37accff20c1ccfdb7

**Comment by johnleider** [comment]
fixed in d795b1e51

**Comment by ElVisPL** [comment]
https://github.com/vuetifyjs/vuetify/issues/11388
Still doesn't work when mocking `breakpoint`

**Comment by Bastczuak** [comment]
yep, it really doesn't work. Please reopen.

**Comment by Bastczuak** [comment]
This is for my people who are coming from google. After reading code and trying around, I know have a working solution for mocking vuetify services in unit tests. Here are some examples.
```js
    const breakpoint = {
      init: jest.fn(),
      framework: {},
      smAndDown: true,
    }
    const vuetify = new Vuetify()
    vuetify.framework.breakpoint = breakpoint
    const wrapper = shallowMount(Component, {
      vuetify,
    })
```
```js
    const goTo = jest.fn()
    goTo.init = jest.fn()
    goTo.framework = {}
    const vuetify = new Vuetify()
    vuetify.framework.goTo = goTo

    const wrapper = shallowMount(Component, {
      vuetify,
    })
```
Your welcome.

@johnleider can we add this to the official documentation?

**Comment by Jatin-Kamboj** [comment]
Hi Dev's

I was facing this same error which got resolved by passing the scss variable n the **Vuetify constructor function** used in the component .

Below is an example
```
/**
 * Vuetify Scss variables used in the component
 */
**const vuetifyVariables = { breakpoint: { xlOnly: true } };**
let vuetify;

```
```
/* Returns the wrapper of the component*/
const getWrapper = (props = {}) => {
  return mount(Component, {
    localVue,
    vuetify,
     });
  };

 let wrapper;
  beforeEach(() => {
    // Pass vuetify variables in the constructor as an argument.
    **vuetify = new Vuetify(vuetifyVariables);**
    wrapper = getWrapper();
  });

```

Hope this resolves the **$vuetify** variables  issue in the jest test cases.

**Comment by dschreij** [comment]
I simply did
```javascript
const goTo = jest.fn()
const wrapper = mountFunc()
wrapper.vm.$vuetify.goTo = goTo
```
which did the trick, but does feel hacky.
