### ISSUE TITLE
[Bug Report] inputs component with props "readonly" does not click

### ISSUE THREAD

**Issue by Yaft** [vuetifyjs/vuetify#11504]
### Environment
**Vuetify Version:** 2.3.0-beta.7
**Last working version:** 2.2.30
**Vue Version:** 2.6.11
**Browsers:** Google Chrome, Mozilla Firefox
**OS:** Windows 10

### Steps to reproduce
add "readonly" prop for input components

### Expected Behavior
input clicked

### Actual Behavior
input dont clicked

### Reproduction Link
<a href="https://codepen.io/st_lemonade/pen/LYpogMo?editors=1010" target="_blank">https://codepen.io/st_lemonade/pen/LYpogMo?editors=1010</a>

### Other comments
render "disabled" attribute in input, although it should not be there

**Comment by Yaft** [comment]
example:
dev - https://dev.vuetifyjs.com/en/components/date-pickers/#month-pickers-in-dialog-and-menu
current - https://vuetifyjs.com/en/components/date-pickers/#month-pickers-in-dialog-and-menu

**Comment by MajesticPotatoe** [comment]
Was discussed this morning in discord. seems a PR for form disable in one of the latest betas cause it
https://github.com/vuetifyjs/vuetify/pull/10325/files#diff-88ed57c748e54f77e38681a94a6834e3L74
https://github.com/vuetifyjs/vuetify/pull/10325/files#diff-8be3f9a9d945aa8db715b9f0df1238d8R127

**Comment by johnleider** [comment]
fixed in ae321cd

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Comment by brugomes** [comment]
Was that published? I'm still facing this problem on `v-input-date `

**Comment by johnleider** [comment]
We don't have a v-input-date component in Vuetify 2.
