### ISSUE TITLE
Tabs: missing pagination controls 

### ISSUE THREAD

**Issue by PeterKnight** [vuetifyjs/vuetify#1341]
### Steps to reproduce
View the pagination example in the official tabs documentation section in a browser.

### Versions
Vuetify 0.14, using Windows (several up to date browsers such as Firefox, Edge, Chromium, Electron etc) and Android (FF)

### What is expected ?
Expecting to see pagination controls and the ability to navigate the items even on a narrow viewport on desktop with the mouse.

### What is actually happening ?
Pagination controls inconsistently show up. Adjusting the viewport width produces inconsistent results (sometimes the pagination pops up but most of the time not) and on mobile no pagination seems to show up (FF on Android). On desktop a narrow viewport produces no pagination and no obvious way to see or navigate to out-of-view menu items.

On mobile:
![mobilevuetifypaginatedtabs](https://user-images.githubusercontent.com/906292/29251559-a62d6b9a-804e-11e7-8f37-7cf0f08465a5.jpg)

Desktop browser on Windows:
![2017-08-13 17_23_14-tabs _ vuetify js - chromium](https://user-images.githubusercontent.com/906292/29251546-772427d0-804e-11e7-88ab-84d476cf0945.jpg)

### Reproduction Link
https://vuetifyjs.com/components/tabs#example-8

**Comment by nekosaur** [comment]
On mobile, there is touch support instead of pagination controls.

I'm looking into desktop issues

**Comment by johnyluyte** [comment]
Can confirm this. In my case, the pagination controls doesn't show up even with normal desktop size (1920*1080).

![vuetifypagenation](https://user-images.githubusercontent.com/4846501/29256042-df31757c-80d9-11e7-9050-51b5d469ff74.png)

**Comment by johnleider** [comment]
Any update on this @nekosaur ?

**Comment by nekosaur** [comment]
Fixed in https://github.com/vuetifyjs/vuetify/commit/7c965d7da885115f67d4d40a1925ccc958583218#diff-e311533536694d39f5b051acd1079d03R11

**Comment by parasaro92** [comment]
This issue is still not fixed. Same problems are coming meanwhile.

**Comment by jacekkarczmarczyk** [comment]
Please create a new issue using https://issues.vuetifyjs.com and provide the reproduction
