### ISSUE TITLE
[Bug Report][3.0.0-alpha.12] Official site doesn't work

### ISSUE THREAD

**Issue by PashaTurok** [vuetifyjs/vuetify#14638]
### Environment
**Vuetify Version:** 3.0.0-alpha.12
**Vue Version:** 3.2.28
**Browsers:** Firefox 95.0
**OS:** Ubuntu undefined

### Steps to reproduce
Official site doesn't work. Open https://next.vuetifyjs.com/en/getting-started/installation and try to click any menu item, for example, components. It doesn't work. I check in FF and Chrome.

### Expected Behavior
It must work.

### Actual Behavior
I doesn't work.

### Reproduction Link
<a href="https://github.com/vuetifyj" target="_blank">https://github.com/vuetifyj</a>

**Comment by KaelWD** [comment]
@nekosaur #14455

**Comment by nekosaur** [comment]
Fixed https://github.com/vuetifyjs/vuetify/commit/445832aa8b522f8b058954c61bd4c1fcc46eddde

**Comment by PashaTurok** [comment]
@nekosaur I still can't get information from the site. Click components -> ok. Click Form inputs & control -> not ok.

**Comment by nekosaur** [comment]
Should work now
