### ISSUE TITLE
[bug] v-text-field still showing error-message when error props is set to false

### ISSUE THREAD

**Issue by Huixiong91** [vuetifyjs/vuetify#1471]
### Steps to reproduce
On the jsfiddle below, key in some value on the email textfield.
Click on the button, the error message gets shown even though the error prop is set to false

### Versions

Vue 2.4.2, Vuetify 0.14.7, Windows 10, Google Chrome.

### What is expected ?

No error-message to be shown when the 'error' prop is set to false.

### What is actually happening ?

The textfield is still in error state, it still shows the error-message props that were set. 
In some use cases, the error-message might be set but simply not meant to be shown yet. e.g. upon reset of the input value. Showing an error is not appropriate as the the textfield is 'new'.

### Reproduction Link
https://jsfiddle.net/jg7hozqn/1/

**Comment by johnleider** [comment]
This has been resolved with ```v-form``` in 0.15

**Comment by florianflock** [comment]
@johnleider the bug is still present in 1.0.4?

As I can see, the errorBag is not resetting.

![image](https://user-images.githubusercontent.com/3831745/36760695-286f4592-1c1c-11e8-8d49-17d19d11cfe4.png)
