### ISSUE TITLE
[Bug Report][2.6.4] v-combobox will have empty value for spaces

### ISSUE THREAD

**Issue by ramseyfeng** [vuetifyjs/vuetify#14874]
### Environment
**Vuetify Version:** 2.6.4
**Vue Version:** 2.6.14
**Browsers:** Chrome 99.0.4844.74
**OS:** Windows 10

### Steps to reproduce
enter some spaces and click the tab, it will remember the empty value

### Expected Behavior
no value should be saved if the trimmed value is empty

### Actual Behavior
blank input will have a chip

### Reproduction Link
<a href="https://codepen.io/ramseyfeng/pen/vYpgMdr" target="_blank">https://codepen.io/ramseyfeng/pen/vYpgMdr</a>

![image](https://user-images.githubusercontent.com/2835062/160089443-1c74d41f-3184-4df8-ade3-e63ea8ec7de0.png)

**Comment by lioneaglesolutions** [comment]
Closing as resolved in V3

https://vuetifyjs.com/en/components/combobox/

**Comment by apodacaduron** [comment]
This is still an issue on the latest vuetify version => https://play.vuetifyjs.com/#eNpdkM2qwjAQhV8lzKab2tJ7cSNVkIK+gOBCXUzrqIFpJiRVFPHd7Y+l1d0334Qw5+ye4F0RL62NbleCGaQVlZaxosXeKJXeJmhti+1QiKlQG3If9ZFlLrnce6UUY04830PWb2DYFRdt/Whk8ZgzTX58eeVKW6bBzHR9mq9/3QUZsj6JMxqDUAWZsDg8SsOrGvWx1WsSd+5ebOiOvoHtQ0ptzsFhuGiRxkOEPmmrxlEb0zWRxqOG4BXCfzSN/qbQQJJECYQnZE/hV6+dO7wBOp5vcA==

Video:
https://github.com/user-attachments/assets/81245813-1e21-44af-bb06-0535f95c3ff4
