### ISSUE TITLE
[Bug Report][3.0.0-beta.1] AutoComplete display value instead of title 

### ISSUE THREAD

**Issue by code2nguyen** [vuetifyjs/vuetify#15097]
### Environment
**Vuetify Version:** 3.0.0-beta.1
**Vue Version:** 3.2.33
**Browsers:** Chrome 101.0.4951.64
**OS:** Mac OS 10.15.7

### Steps to reproduce
1. Select 'Foo' from menu
2. AutoComplete Textinput displays 'Foo' as expected
3. Click on the browser, 

### Expected Behavior
AutoComplete Textinput displays 'Foo' after on losing focus 

### Actual Behavior
AutoComplete Textinput displays 'Foo-value' after on losing focus 

### Reproduction Link
<a href="https://codepen.io/Code2Nguyen/pen/jOZyrvq?editors=1010" target="_blank">https://codepen.io/Code2Nguyen/pen/jOZyrvq?editors=1010</a>

**Comment by Dranero** [comment]
When 'multiple' is enabled, the value is shown permanently. 
I had the same issue, but could not track it down completly.
The props for the chips in the textfield are:
```
{
  "props": {
    "modelValue": true
  },
  "selection": {
    "title": "foo-value",
    "value": "foo-value",
    "index": 0
  }
}
```
So i guess there are two bugs. One that displays the title when the focus is given in 'single' mode and one that injects the value twice into the props.

**Comment by AntoninBeaufort** [comment]
I've opened a similar issue with another problem that you can see here: https://github.com/vuetifyjs/vuetify/issues/15151#issuecomment-1140828296
As of 3.0.0-beta.3 it seems that your problem has been fixed.

**Comment by Dranero** [comment]
Well, the value isn't shown anymore but vanishes completly on the same occasions. So I guess it is not fixed. :)

**Comment by lunatiqqc** [comment]
For me, the chips show the item value instead of the title on blur of the autocomplete component
