### ISSUE TITLE
[Documentation] next.vuetifyjs.com not working 

### ISSUE THREAD

**Issue by kanopa** [vuetifyjs/vuetify#15170]
### Environment

**Browsers:** Chrome 101.0.4951.64
**OS:** Mac OS 10.15.7

### Steps to reproduce
Just open docs for next version

### Expected Behavior
Documentation

### Actual Behavior
🙁

### Reproduction Link
<a href="https://next.vuetifyjs.com/en/getting-started/installation/" target="_blank">https://next.vuetifyjs.com/en/getting-started/installation/</a>

![image](https://user-images.githubusercontent.com/42976537/171061232-0008ecfe-d30a-48de-877e-c89895e86fb8.png)

**Comment by MajesticPotatoe** [comment]
caused by bd6fe14, pushed old working commit for the time being so should be working (may need to clear cache/sw)

**Comment by kanopa** [comment]
> caused by [bd6fe14](https://github.com/vuetifyjs/vuetify/commit/bd6fe140edb1f9d21c9ea959d38a8a7c2344d71e), pushed old working commit for the time being so should be working (may need to clear cache/sw)

Thanks!

**Comment by JeffreyVRiemsdijk** [comment]
It is still broken, a fix after 14 hours would have been nice.
