### ISSUE TITLE
$attrs is undefined

### ISSUE THREAD

**Issue by mirhat** [vuetifyjs/vuetify#1586]
### Steps to reproduce
Create v-text-field
### Versions

vue 2.8.2
vuetify 0.15.0-beta.5

### What is expected ?

There should be input field
### What is actually happening ?

Input field is not showing and I am getting error 

> TypeError: Cannot read property 'id' of undefined
>     at VueComponent.genLabel (vuetify.js:829)
>     at VueComponent.boundFn [as genLabel] 

Here is genLabel function:
```
genLabel: function genLabel() {
      return this.$createElement('label', {
        attrs: {
          for: this.$attrs.id
        }
      }, this.$slots.label || this.label);
    },
```
### Reproduction Link

https://jsfiddle.net/9jht1sbk/1/

**Comment by mirhat** [comment]
Input field is showing if I there is no label property on v-text-field

**Comment by KaelWD** [comment]
> vue 2.8.2

1. Are you from the future?
2. That fiddle is using 2.2.1, it works fine with 2.4.2: https://jsfiddle.net/rs4b9by6/

**Comment by johnleider** [comment]
This issue should have been resolved from the latest release. I am unable to reproduce it with the given information as @KaelWD pointed out, you must be on vue@2.4 branch.

If this is incorrect and you are still able to reproduce it, please provide additional reproduction steps, otherwise I'll considered this closed.

**Comment by mirhat** [comment]
It is my mistake, I had wrong version of vue. It is working now.
Thank you!

**Comment by bradstewart** [comment]
There's still an issue here. I believe it's related to https://github.com/vuejs/vue/issues/6263, not Vuetify specifically, but in case someone else comes looking... 

I'm seeing this error when using render functions and supplying a `label` prop with `vue@2.4.2` and `vuetify@0.15.3`:

```javascript
//...
return h('v-text-field', {
  props: {
    label: meta.label,
    hint: meta.hint,
    required: meta.required,
    value: this.model[meta.field],
  },
  on: {
    input: (value) => {
      this.model[meta.field] = value
    },
  },
})
//...
```

Removing the `label` key from the `props` object resolves it. I'll extract it into a fiddle later today, if I find a spare minute.

**Comment by johnleider** [comment]
Is it reproduce-able in a codepen?

**Comment by bradstewart** [comment]
I have some work to knock out right now, but I'll attempt to reproduce it in a fiddle/codepen later today.

**Comment by jay-zahiri** [comment]
+1
