### ISSUE TITLE
[Bug Report][3.0.0-beta.14] error TS2305: Module '"vue"' has no exported member 'JSXComponent'.

### ISSUE THREAD

**Issue by devigner** [vuetifyjs/vuetify#15968]
### Environment
**Vuetify Version:** 3.0.0-beta.14
**Last working version:** 3.0.0-beta.13
**Vue Version:** 3.2.41
**Browsers:** Firefox 107.0
**OS:** Mac OS 10.15

### Steps to reproduce
pnpm build
An error occures: error TS2305: Module '"vue"' has no exported member 'JSXComponent'.

### Expected Behavior
The build is successful

### Actual Behavior
The build fails

### Reproduction Link
[https://codesandbox.io/s/pedantic-shockley-8rf8o8?file=/src/main.js](https://codesandbox.io/s/pedantic-shockley-8rf8o8?file=/src/main.js)

**Comment by devigner** [comment]
Unfortunately creating a demo is not that easy. Our huge application throws the error. 

`> vue-tsc --noEmit && vite build

node_modules/.pnpm/vuetify@3.0.0-beta.15_3nim2poxfuixesidb7kfxqvhz4/node_modules/vuetify/dist/vuetify.d.ts:2:51 - error TS2305: Module '"vue"' has no exported member 'JSXComponent'.

2 import { Ref, DeepReadonly, VNodeChild, PropType, JSXComponent, CSSProperties, ExtractPropTypes, ComputedRef, nextTick, ComponentInternalInstance, Prop, WritableComputedRef, InjectionKey, UnwrapRef, DirectiveBinding } from 'vue';
                                                    ~~~~~~~~~~~~

node_modules/.pnpm/vuetify@3.0.0-beta.15_3nim2poxfuixesidb7kfxqvhz4/node_modules/vuetify/lib/components/index.d.ts:2:69 - error TS2305: Module '"vue"' has no exported member 'JSXComponent'.

2 import { Ref, DeepReadonly, VNodeChild, PropType, ExtractPropTypes, JSXComponent, ComputedRef, nextTick, ComponentInternalInstance, Prop, WritableComputedRef, CSSProperties, InjectionKey, UnwrapRef } from 'vue';
                                                                      ~~~~~~~~~~~~

node_modules/.pnpm/vuetify@3.0.0-beta.15_3nim2poxfuixesidb7kfxqvhz4/node_modules/vuetify/lib/iconsets/mdi-svg.d.ts:1:10 - error TS2305: Module '"vue"' has no exported member 'JSXComponent'.

1 import { JSXComponent, PropType } from 'vue';
           ~~~~~~~~~~~~


Found 3 errors in 3 files.

Errors  Files
     1  node_modules/.pnpm/vuetify@3.0.0-beta.15_3nim2poxfuixesidb7kfxqvhz4/node_modules/vuetify/dist/vuetify.d.ts:2
     1  node_modules/.pnpm/vuetify@3.0.0-beta.15_3nim2poxfuixesidb7kfxqvhz4/node_modules/vuetify/lib/components/index.d.ts:2
     1  node_modules/.pnpm/vuetify@3.0.0-beta.15_3nim2poxfuixesidb7kfxqvhz4/node_modules/vuetify/lib/iconsets/mdi-svg.d.ts:1`

**Comment by KaelWD** [comment]
Fixed by e23e92c69

**Comment by devigner** [comment]
Thanks, that is awesome!

**Comment by crystalfp** [comment]
This annoying error still appear with Vuetify 3.6.12 when setting `"skipLibCheck": false` in tsconfig.json and running `npx vue-tsc`
```
node_modules/vuetify/lib/blueprints/index.d.mts:1:40 - error TS2724: '"vue"' has no exported member named 'JSXComponent'. Did you mean 'Component'?

1 import { Ref, ComponentPublicInstance, JSXComponent, PropType } from 'vue';
                                         ~~~~~~~~~~~~

node_modules/vuetify/lib/components/index.d.mts:2:124 - error TS2724: '"vue"' has no exported member named 'JSXComponent'. Did you mean 'Component'?

2 import { Ref, DeepReadonly, ComponentPropsOptions, ExtractPropTypes, VNodeChild, VNode, ComponentPublicInstance, PropType, JSXComponent, ComponentInternalInstance, ComputedRef, Component, EffectScope, CSSProperties, WritableComputedRef, UnwrapRef, nextTick, Prop, InjectionKey } from 'vue';

     ~~~~~~~~~~~~

node_modules/vuetify/lib/components/VAlert/index.d.mts:2:51 - error TS2724: '"vue"' has no exported member named 'JSXComponent'. Did you mean 'Component'?

2 import { ComponentPropsOptions, ExtractPropTypes, JSXComponent, PropType } from 'vue';
                                                    ~~~~~~~~~~~~
```
and continues for all components loaded.
