### ISSUE TITLE
v-toolbar overlap on v-navigation-drawer

### ISSUE THREAD

**Issue by jbije** [vuetifyjs/vuetify#1611]
### Versions
0.15.2

### What is expected ?
Layout  —  Pre-defined 3

The v-navigation-drawer both permanent, right side v-navigation-drawer is on clipped

### What is actually happening ?
The left side v-navigation-drawer overlap by v-toolbar while the right side v-navigation-drawer is on clipped.

### Reproduction Link
issue: https://codepen.io/jbije/pen/jLoqNe

**Comment by johnleider** [comment]
This is unfortunately a downside to the current implementation of the layout system. While this still does not work on the new system, I can take this information into consideration and see if I can make it happen. I'm going to tag it for 0.16 but that may slip, we'll see.

**Comment by johnleider** [comment]
This has been resolved with the new layout system.

**Comment by davi5e** [comment]
I'm having this issue still (vuetify@0.16.9)

Are there any steps to take in order to fix this problem?

In the [sandbox](https://vuetifyjs.com/examples/layouts/sandbox) this doesn't occur, by the way, but there is no way to check the source code to compare with my own.

Also, should the reproduction link reflect said changes? (I'm new to codepen...) Because the link OP provided is still very much like my ongoing issue

**Comment by jacekkarczmarczyk** [comment]
Source code of the sandbox is here: https://github.com/vuetifyjs/docs/blob/dev/examples/layouts/sandbox.vue
If there's no issue in the docs then it's something with your code, you may want to visit official discord channel https://chat.vuetify.com to get help (create first a codepen with your code)

**Comment by davi5e** [comment]
the codepen the OP posted is exactly like my current problem...

**Comment by jacekkarczmarczyk** [comment]
If you're code looks like in this codepen then it must be updated to be compatible with 0.16 version 
https://github.com/vuetifyjs/vuetify/releases/tag/v0.16.0

**Comment by davi5e** [comment]
Thanks, will look into that!
