### ISSUE TITLE
[Bug Report][3.3.11] VDataTable - Unable to set initial page

### ISSUE THREAD

**Issue by hackel** [vuetifyjs/vuetify#17966]
### Environment
**Vuetify Version:** 3.3.11
**Vue Version:** 3.3.4
**Browsers:** Firefox 117.0
**OS:** Linux x86_64

### Steps to reproduce
Set the `page` prop to something other than 1. (e.g. from a URL query parameter)

### Expected Behavior
Table displays the given page of the table.

### Actual Behavior
The `page` prop is always changed back to 1 on load.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqNV11P8zYU/itWpKlha9JvXoiA8Y6NjTFpXEyTJsqFm5rWw4kj2y3rUP/7e+zYcZIGtb1p4vOc4+d82nn+CL4WRbzdkCAJrhTJCoYVuZnnCF1toyVWOFJ4wUgkidgSodcR2kYZXxKWUMDLqCAiKvCKXM8Ds/BExBO8zoMSnKwJXhIhQWyfKkmpz0i+UmsQK64we9BrTQSIyt2bMsbxkuYrkNqnSiIJFqm2WD649ZRhqY0RRrZYUZ5HIyfS+0RbzDbaixxnnr31bOwWbjcFRIUkvNAWtDm9e43ZzdWgI3AQ0atBLbzwKlNBC2VCnYIlhZZEAlhJdI2ey80+yj+ENKUE9e4F/5/k6B++2gjV6ztpihkXlMgEjWaX1eorVgk6j4c1mFgAZjytVgrBFaF5gqY1GBUcVnojZ39v/9tkfieM7dCC4LyLyeTLrMlkeMjksoNJHWaZDI8xeaTqEXfGYza6aLIYdwTk3DOtaHxpkzg/RuIXKC8qukiMz8dNEqOurEwOSdRhlsaXYzR+hUYgYiGg1TrTMjs/zmXqi6jiMon9oquQozF5SAlKgUqGJM6X7zRdd8Zn4qNtOF0eUqpBakXrY3Zq0f7BGaMFLzpjc9nK0zD2C65kfT35km2zGB9jcbcpUvxGOkkMW30zib3rrmBPC8bFMRq/8ZzsUp4tuohMh63WmRxG46KDyHnsHbBEprNjTH7m+aazgaezVk7Gs8PimI264nFQr+NWXl70GHbD9x7y8fXpAWav5YblLk/RK1HpOvxA+hjom2PCnW99JLlQP+3Q/sy7I4jaiBzl5B09CZ5RSUJBJGdbgq5vPAwhSdRfNCN8o8LwrCVzlKTCQgGhUG+OIjQ6Q983KByqkHwJCqXiD0ewRgpod+zEktGUhGdlVNyPvqKwdDQuD+qatw2ygHkkO727QT8PX+I3svsM+qeAm0ADzPVKE24YxhoShriPFoeB8kbx3/r0Bov42VKB9HYBFw64+BRos1jjeX2NehCntId+dAYit2XiHiIraprbQ0Brb83olpQgvzSHe4HOnfXZpMLksa+T2kqKrSmoSwNPvIU+MreoxNopU9bgsO+j2XBYLThR2RKWHvmvAN+hMl7xhikXcn2pSVBZrmGVhnqRQStWTWcve4m7yzTaXv8UVcz0fll/KBwNhytoDLGFI+zMDwPTjIyudAubiDRFOkv6opXAfGCSNGRQgKCkZ0xdxw0hw6iicWdnTq9v1dwQggW3PWSi94n6PQYPNG2rDcPqNMU7PcMaqmaqnaYMQ0aPu4a6HYGnGXiA0YjC77y2npWfq75UT+XVGhA+srVLOmTdQ+31PEFKbHx+/G3fn6D7M/uQEbXmS5BUFVPdsk8fxmV7cUZixldhr7IA7mkLtZ5Qawq9UtKEHtQ8vdCeDPFJR0Gs1iQP6zXomtR2pmZ4OMUMgVr83CDoQPm4aab6pQPkfTFN0ZpA7tEPgca5CIirQfV1EvQDRvM3Gf8reQ4fiYb5PEglfO9UzQ3fdkoVMhkM0mUOSPg6pFsR50QN8iIbwOeloq+720k8iUejwZJK5dYihhcyNtbsmbyHHWmmB1CU4aK1bSkwW9sQzgOwpN+PcLgF2EBscgXHbrTkmSEzLbnUlmMis2gh+DtkA4zMAxsas40mfMJWR92FPQ5sD8r0RwJajgg4Ck90qaVWd6slOnDNJnsf7PuBUYPIl5yDl29YyqzN)

**Comment by websitevirtuoso** [comment]
Yes I can confirm. Issue persist and datatable reset it always to 1 on mounting. I think this is easy fix

**Comment by nekosaur** [comment]
Set the initial value of `items-length` prop to `x * items-per-page` where `x` is the page you want to start on.

I'm not sure if we should call this a bug or not. Maaybe we'd want different behavior in -server variant. I'll keep this open for now.

**Comment by HristoAntov** [comment]
I can confirm that this is a bug and it's present from August this year. The workaround with the `items-length` prop not only doesn't fix anything, but completely messes up the pagination behavior

It practically makes using the table pagination in sync with url parameters impossible.

**Comment by K4GR** [comment]
I can offer a temporary and very strange but working solution. If you add to your table
`@update:page="() => {}"`
then everything starts working correctly

[playground](https://play.vuetifyjs.com/#eNqNV9tu4zYQ/RXCQGG5tRT5mkSI027Tpk1ToHkoChRJHmh5YgtLiwJFedcb+N93KJKiJCuw/SJp5szwcG6kn997uYgvPmVZsCugF/VuJGwzRiXcvqSE3Oz8FZXUl3TJwM9B7EAoOSE7f8tXwKIE8bmfgfAzuobFS68UPIF4ws+XngZHG6ArEDmqzVul0fYM0rXcoFpySdmDkjURqNKrN3WM01WSrlFr3ipNDlTEyqN+sfKY0Vw5AwY7KhOe+iOrUuv4O8oKtYuUbh17s7OxFfxSZBgViHimPCh3avUGMwsxpt6ALG7J+0Grb28uOuKKAb+5qEUfP/NYJJksMxHjQpKsIEewzMmCPOuF3vWDEMU4Iv17wb9BSv7n60LI/tBqY8q4SCCPyGh2XUnfqIzIPAhrMLFEzHhaSTLBJSRpRKY1WCI4Svoj6/9gnm0yfwFje7IEmnYxmVzOmkzCYybXHUzqMMMkPMXkMZGPtDMes9FVk8W4IyBzx7SicdkmMT9F4nesvkR0kRjPx00So66sTI5J1GGGxuUpGn9gn4BYCuzEzrTM5qe5TF0RVVwmgRPaCjkZk4cYSIxUtiSn6epLEm864zNx0S45XR9TqkFqRetidm7R/s0ZSzKedcbmupWnMHACW7KunlzJtlmMT7G4K7KYfoZOEmGrbyaB27ot2POCcXWKxp88hX3Mt8suItOw1TqT42hcdRCZB24Dhsh0dorJbzwtOht4OmvlZDw7Lo7ZqCseR/U6buXlVY1hO3zvMR+fnh5w9hpuNN+nMXkDGW+8d6JG/bA8RezxNyQ5F/LXPTkM3HYEyEKkJIUv5EnwbZKDJyDnbAflEWFhhOQg/022wAvpmePD6SylXFIhkZCnFic+GQ3Ijw0KxyaQrtBAG/50AltqEW2PnSBnSQzeQEfF/pI34umNBvocr+22QRYxj7BXq5fo5/A1+Az7j6D/CLwoNMBcSZrwkmGgIJ5Hh2R5HCjnlP6nDnf0SJ8NFUxvF3BpgcsPgSaLNZ6LBeljnOI++dk68O2SkX3xjarp7oABrX01o6spYX6TFO8FKndmz2UqyjwOVVJbSTE1hXVZwiPnYUjKS1Zk/OiUNTgchmQWhpXAqnRLGHrwNcO9Y2W80YJJG3J1qYmILlevSkO9yLAVq6Yzd8HI3mUaba9+MpGs7H1df8QbheEaG0Ps8AgbuGFQNiNL1qqFy4g0VSpL6qIV4XxgOTR0WIBopGZM3cYOoZJRRePOzJz+0JjZIYQCuzxmov+B+T3FHSjaxhqH1XmGd2qGNUzLqXaeMQ4ZNe4a5mYEnufgAUcj8X5w1mpWfmz6Wr3pmzciXGRrd3jMuoOa23tEpChcftyfAXeCHgbmZQtyw1eoqSqmuoSfP4x1e3EGAeNrr195wO0pD7WekJsEe0XTxB5UPJ3SnAzBWUdBIDeQevUatE1qOlMxPJ5iJYFa/Owg6EC5uCmm6qMD5PZSNkVrAtlXNwQa5yIibi6qfye9w7A3CSbBtKefo1Hv9TuQihHc)

**Comment by KozakoPolako** [comment]
> I can offer a temporary and very strange but working solution. If you add to your table `@update:page="() => {}"` then everything starts working correctly
> 
> [playground](https://play.vuetifyjs.com/#eNqNV9tu4zYQ/RXCQGG5tRT5mkSI027Tpk1ToHkoChRJHmh5YgtLiwJFedcb+N93KJKiJCuw/SJp5szwcG6kn997uYgvPmVZsCugF/VuJGwzRiXcvqSE3Oz8FZXUl3TJwM9B7EAoOSE7f8tXwKIE8bmfgfAzuobFS68UPIF4ws+XngZHG6ArEDmqzVul0fYM0rXcoFpySdmDkjURqNKrN3WM01WSrlFr3ipNDlTEyqN+sfKY0Vw5AwY7KhOe+iOrUuv4O8oKtYuUbh17s7OxFfxSZBgViHimPCh3avUGMwsxpt6ALG7J+0Grb28uOuKKAb+5qEUfP/NYJJksMxHjQpKsIEewzMmCPOuF3vWDEMU4Iv17wb9BSv7n60LI/tBqY8q4SCCPyGh2XUnfqIzIPAhrMLFEzHhaSTLBJSRpRKY1WCI4Svoj6/9gnm0yfwFje7IEmnYxmVzOmkzCYybXHUzqMMMkPMXkMZGPtDMes9FVk8W4IyBzx7SicdkmMT9F4nesvkR0kRjPx00So66sTI5J1GGGxuUpGn9gn4BYCuzEzrTM5qe5TF0RVVwmgRPaCjkZk4cYSIxUtiSn6epLEm864zNx0S45XR9TqkFqRetidm7R/s0ZSzKedcbmupWnMHACW7KunlzJtlmMT7G4K7KYfoZOEmGrbyaB27ot2POCcXWKxp88hX3Mt8suItOw1TqT42hcdRCZB24Dhsh0dorJbzwtOht4OmvlZDw7Lo7ZqCseR/U6buXlVY1hO3zvMR+fnh5w9hpuNN+nMXkDGW+8d6JG/bA8RezxNyQ5F/LXPTkM3HYEyEKkJIUv5EnwbZKDJyDnbAflEWFhhOQg/022wAvpmePD6SylXFIhkZCnFic+GQ3Ijw0KxyaQrtBAG/50AltqEW2PnSBnSQzeQEfF/pI34umNBvocr+22QRYxj7BXq5fo5/A1+Az7j6D/CLwoNMBcSZrwkmGgIJ5Hh2R5HCjnlP6nDnf0SJ8NFUxvF3BpgcsPgSaLNZ6LBeljnOI++dk68O2SkX3xjarp7oABrX01o6spYX6TFO8FKndmz2UqyjwOVVJbSTE1hXVZwiPnYUjKS1Zk/OiUNTgchmQWhpXAqnRLGHrwNcO9Y2W80YJJG3J1qYmILlevSkO9yLAVq6Yzd8HI3mUaba9+MpGs7H1df8QbheEaG0Ps8AgbuGFQNiNL1qqFy4g0VSpL6qIV4XxgOTR0WIBopGZM3cYOoZJRRePOzJz+0JjZIYQCuzxmov+B+T3FHSjaxhqH1XmGd2qGNUzLqXaeMQ4ZNe4a5mYEnufgAUcj8X5w1mpWfmz6Wr3pmzciXGRrd3jMuoOa23tEpChcftyfAXeCHgbmZQtyw1eoqSqmuoSfP4x1e3EGAeNrr195wO0pD7WekJsEe0XTxB5UPJ3SnAzBWUdBIDeQevUatE1qOlMxPJ5iJYFa/Owg6EC5uCmm6qMD5PZSNkVrAtlXNwQa5yIibi6qfye9w7A3CSbBtKefo1Hv9TuQihHc)

Except of page change, unfortunately

**Comment by Melvinvmegen** [comment]
I really appreciate your work but i have to say I really don't understand how this is labeled as **maybe**. How are we supposed to save the pagination in the navigation if the table keeps resetting to the first page?

**Comment by websitevirtuoso** [comment]
This is bug and we need to fix it to implement this ability.
Any help and PR are welcome

**Comment by naglafar** [comment]
+1 on this.

I cant initialise a table on any page other than 1.

**Comment by klondikemarlen** [comment]
> +1 on this.
> 
> I cant initialise a table on any page other than 1.
> 
> **Workaround:** Don't render the table until you have loaded the data. Use a skeleton load while you wait.

Thanks @naglafar. I can confirm that delaying render until after load completes works for me.

```vue
<template>
  <v-skeleton-loader
      v-if="isLoading"
      type="table"
    />
    <v-data-table-server
      v-else
      v-model:items-per-page="itemsPerPage"
      v-model:page="page"
      :headers="headers"
      :items="items"
      :items-length="totalCount"
      :loading="isLoading"
    />
</template>
```

Assuming items are loaded like
```ts
async function fetch() {
  isLoading.value = true
  try {
     items.value = await fetchSomeItems()
  } finally {
     isLoading.value = false
  }
}
```
where isLoading resolves after items have fully loaded.

**Comment by klondikemarlen** [comment]
Is this just a bug in https://github.com/vuetifyjs/vuetify/blob/a95aeb2ce257bf08f5e0b4a132b9a0641cd0dcf9/packages/vuetify/src/components/VDataTable/composables/paginate.ts#L84?

Should it be something like `page.value = page.value || 1`?

**Comment by klondikemarlen** [comment]
I've found a work-around for the flicker introduced by using v-if with a skeleton loader.
You can ignore updates to `page` while `isLoading` is true, assuming that `isLoading` resolves after `items` have been updated.

```vue
<template>
  <v-data-table-server
    v-model:items-per-page="itemsPerPage"
    :page="page"
    :headers="headers"
    :items="items"
    :items-length="totalCount"
    :loading="isLoading"
    @update:page="updatePage"
  />
</template>

<script setup lang="ts">
// ... other code and variable setup

function updatePage(newPage: number) {
  if (isLoading.value) return

  page.value = newPage
}

async function fetch() {
  isLoading.value = true
  try {
    items.value = await fetchSomeItems()
  } finally {
    isLoading.value = false
  }
}
</script>
```
See https://github.com/icefoganalytics/internal-data-portal/commit/49fbafc5e354b2e8bbaacd6752840d405515adcd

**Comment by webdevnerdstuff** [comment]
The problem is that the `search` prop is set to an empty string as the default. If you set it to `undefined` (which is the default), you can set the initial page.

https://play.vuetifyjs.com/playgrounds/Krx_8w

**Comment by Ribeiro-Tiago** [comment]
Still have this issue as of 3.6.9

**Comment by matejbujnak** [comment]
I've implemented a solution where an initializing value is used to bypass the first @update:options="updateOptions" event. This prevents unintended modifications during the initial table setup.

<script setup>
import { ref } from 'vue';

const initialLoad = ref(true); // Flag to indicate initial load

async function updateOptions(params = {}) {
  if (initialLoad.value) { 
    initialLoad.value = false; // Disable after initial update
    params.page = getPage();   // Apply initial page setting
  }
  // ... (Rest of your update logic)
}
</script>

<template>
  <v-data-table 
    v-model:page="page"
    @update:options="updateOptions"
    ...>
    </v-data-table>
</template>
`

**Comment by matejbujnak** [comment]
I've implemented a solution where an initializing value is used to bypass the first @update:options="updateOptions" event. This prevents unintended modifications during the initial table setup.

`<script setup>
import { ref } from 'vue';

const initialLoad = ref(true); // Flag to indicate initial load

async function updateOptions(params = {}) {
  if (initialLoad.value) { 
    initialLoad.value = false; // Disable after initial update
    params.page = getPage();   // Apply initial page setting
  }
  // ... (Rest of your update logic)
}
</script>

<template>
  <v-data-table 
    v-model:page="page"
    @update:options="updateOptions"
    ...>
    </v-data-table>
</template>`

**Comment by olivierpoisson** [comment]
One way that could work for some people is to use a watcher instead of listening to the `@update:options` event. What I mean:
```js
<v-data-table-server
    v-model:page="options.page"
    v-model:items-per-page="options.itemsPerPage"
/>

const options = ref({
  page: 1,
  itemsPerPage: 10,
});

watch(options, value => {
    // Fetch your data.
  },
  { deep: true }
)
```
This allows you to check the query in `onMounted()` and changing the options ref once, so that you will only make 1 backend call
```js
onMounted(() => {
    // Pseudo code. This will trigger the watcher only once
    options.value = {
        page: query.page,
        itemsPerPage: query.itemsPerPage
    }
});
```

**Comment by bierik** [comment]
Still having this issue. What is the status here? @webdevnerdstuff's PR does not seem to resolve the issue as far as I can tell.

**Comment by blakegearin** [comment]
Still having this issue on `3.7.3`

The only reliable way I'm able to avoid this bug seems to be setting a default of `null` instead of a number value. 

```vue
<template>
  <v-data-table-server
    :items-length="itemsLength"
  >
  </v-data-table-server>
</template>

<script setup>
import { ref } from 'vue';

const itemsLength = ref(null);
</script>
```

I believe this works because when items length is `null` no comparison to the page number can be made, so the page number's value remains intact until items length is populated.
