### ISSUE TITLE
[Bug Report][3.4.9] v-dialog: @keydown.esc does not trigger when in persistent mode

### ISSUE THREAD

**Issue by douglasg14b** [vuetifyjs/vuetify#18989]
### Environment
**Vuetify Version:** 3.4.9
**Vue Version:** 3.4.5
**Browsers:** Firefox 120.0
**OS:** Windows 10

### Steps to reproduce
1. Create a dialog with `persistent`
2. Add `@keydown.esc` to the dialog
3. Open the dialog
4. Hit `esc`

### Expected Behavior
The event is fired & handled

### Actual Behavior
It is not

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqtU01vwjAM/StWLtukFfbFgQkQSLvvsN3WHbLUQESbRIn5EuK/z2mhLR+HHXZq8vzyXPvZXzsRvOpOnOuslihexYCwcLkkHKUGYLBKpHPlsbwoa0hqg/4AleAPGVA2t36YCud1If02FZBJv4CxyrVaMJ5pmdsZDIH8ElMxgneHBt4qdNAtRdqaFf8IAKySwmaY10qpaGIOfdCB0FCDjRe4zezadDCodvqpzAPnb4iF3CRrndGcWU/9hyZU/01VuPRZC6mxhDTlCCqXIbAC4YaSeS8W+ImB2gU27Os6/HL0YQvkhxtqHkT4Gl8q0taEk1gZDU4q9icqHI4XlLZhM49sRDQLTfLIvl1adujZmQ5wcUHG52f6Z2b+d9bJ31LWHbxs1DHUzBsDVd7jpEfGyahHpNqEQbe1IXwNymtHEJCW1aLowllPsAOPU9jD1NsCbni5biIduAWGB6Muk0m3Zal3UboSYxmxvxfPnZdOT1Tfvvj+BVZiFpw=)

### Other comments
This appears to have worked in older versions of vuetify 

For example, this issue has it working but only if the dialog itself is clicked: https://github.com/vuetifyjs/vuetify/issues/13882

**Comment by FiXiLiX** [comment]
Looking at VOverlay code it looks like this is expected behavior:
![image](https://github.com/vuetifyjs/vuetify/assets/50845827/392bf15c-1874-4dd3-a81d-68411fcc39c7)
This piece of code explicitly blocks that kind of behavior. It even intentionally add animation that can be seen in your example.
Documentation for `persistent` says:
"Clicking outside of the element or pressing esc key will not deactivate it."
Different issue is that `keyup` and `keydown` are not passed at all when applied to v-dialog
`<v-dialog
        v-model="dialog"
        @keyup.enter="dialog = false"
        max-width="290"
      >`
Without `persistent` also won't work
while
`<v-dialog
        v-model="dialog"
        @click="dialog = false"
        max-width="290"
      >` works
Workaround also does not look very nice plus you need to be *really* careful to also remove Event Listener when closing modal with buttons (Disagree/Agree) 
![image](https://github.com/vuetifyjs/vuetify/assets/50845827/ea0b926b-0c2b-4e06-8aac-78bf464b7e2f)

**Comment by douglasg14b** [comment]
> Clicking outside of the element or pressing esc key will not deactivate it.

That states that it will not deactivate it, *not* that the events will not be emitted. This is very different than "closing the dialog", I may want to wave an annoying flashy thing at the user when they hit `esc` because I can, and not close the dialog, for instance.

**Comment by fhueter** [comment]
Bumping this bug up because as it is implemented at the moment we can not use `persistent` any more and therefore lose the ability do disable clicking outside the dialog with keeping the self-made "close-on-esc" functionality.

**Comment by KaelWD** [comment]
Fixed with #18779

**Comment by douglasg14b** [comment]
Thanks @KaelWD !!

**Comment by b-maslennikov** [comment]
Looks like the problem [still exists](https://play.vuetifyjs.com/#eNpNUMtOwzAQ/JWVLwWJNL1wQSkqEnckroSDcTbU6vohe50WVf13HKdJe7E0j90Z79dZxKDqN+/XQ0LxIhpG40kyvrYWoBmqH7bAeOJtKz48WnjXktxvK2CnSKtDprvCwBY4JMxCPY9OwggAhsq4Dmmxt2LijTxVR93xPivPm81MewxRR0bLE94d8C/5NUZ1H9hLijlxtJTMkqpk6IA1E2br0vZaqp5bZdjUd3/NMKqgPUNETr64tfEuMJwh7iWRO35iDxfogzOwytdajVMAytnIsHS6eR9KvccxaFqdl4rLk01E5fn+B1evf8o=) in the latest version
