### ISSUE TITLE
v-date-picker selects wrong date (probable Daylight Savings error)

### ISSUE THREAD

**Issue by travbid** [vuetifyjs/vuetify#1939]
### Steps to reproduce
Change timezone to Auckland, New Zealand
Implement a v-date-picker component.
Click on a day after September 23rd, 2017.

### Versions

Vuetify: 0.15.7
Vue: 2.4.2
OS: Debian Stretch, Windows 10
Browsers: Firefox, Chrome
Timezone: Auckland, New Zealand

### What is expected ?

The date that is clicked becomes the selected date.

### What is actually happening ?

When clicking on a date after September 23rd 2017, the day before is actually selected.
This also seems to happen with dates before April 2nd 2017, indicating an issue with Daylight Savings (see my timezone above).

### Reproduction Link

[https://codepen.io/anon/pen/ZXyGLp](https://codepen.io/anon/pen/ZXyGLp)
[https://vuetifyjs.com/components/pickers](https://vuetifyjs.com/components/pickers)

**Comment by KaelWD** [comment]
Here's a codepen with 0.16, is it still broken?

https://codepen.io/anon/pen/JrJMLX

**Comment by tallgoose** [comment]
Yes, still broken.

**Comment by travbid** [comment]
Yes, still broken

**Comment by KaelWD** [comment]
Reopening, this broke everything.

**Comment by peluprvi** [comment]
Remember on js you always choose a local date.
On 0.15 I'm using the Date object and parse or format the date with moment.js.

The follow example can be useful for testing and developing:
https://codepen.io/anon/pen/QqqVor

If necessary, I can add this example or something like that on vuetify docs.

**Comment by KaelWD** [comment]
Hopefully fixed with #1986

**Comment by eelcowen** [comment]
Still having this problem with Vuetify 0.16.4, Chrome 61, OSX and locale NL-nl

**Comment by zevektor** [comment]
Don't know if this is related, but even the month datepicker is behaving weirdly, only on Chrome.
(As you can see March is repeated twice)

![Imgur](https://i.imgur.com/RZPl4wO.png)

**Comment by jacekkarczmarczyk** [comment]
Please check in 0.17.0-beta.1

**Comment by zevektor** [comment]
@jacekkarczmarczyk  working fine with 0.17 beta!
