### ISSUE TITLE
[Bug Report][3.6.13] Inputs plain variant has a solid background color

### ISSUE THREAD

**Issue by simionato-mobisec** [vuetifyjs/vuetify#20210]
### Environment
**Vuetify Version:** 3.6.13
**Vue Version:** 3.4.33
**Browsers:** Firefox 128.0
**OS:** Ubuntu undefined

### Steps to reproduce
1. Create two v-text-field with variant prop set to "plain".
2. Add `bg-color="red"` to one of them.

### Expected Behavior
Bg color is ignored since the variant is set to plain.

### Actual Behavior
Bg color is taken into account.

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqtUs1u2zAMfhVBF29AbG0otkOQFt2eoehl2kGxGUeF/iDRbosg715aVhr359ACvUgi+ZGf+JH/DjzFVowDoN49NneJr7m2wUdkB9ZGUAi3c4wd2S56y6qCraSTDh4ytPUuISsBdvky8dtBOsZwDxbWLL8Z62CnBoM3s7Myut9jtZpjQkz3MVsFl54Tb/+iu/F9b861ZufCZKw1KlFO1Q4JvT0VPhU93dN5/C4dX2UN/oTQUAskwAbBBkMdXE2wzVirEPIzG9QsKu0gFld2IjxgvdNguvMvQoQArqu1I3CtKe9Sctvp2qrekTCSn7HbnuoaHwkRoVtGRhW1ckgB+pJ259DVRix5v/I3n+ScnC9VmTyzaBuxEJOUnpeLSAMtm3ekdp6bLIEk+fMkJadxTLbke8SQ1kK0naO0DoweY+MAhQtWXBNMxMGhtlB33l5fNL+aH7UyYa+aC9HphMtwA8nW2+jvE0QqJnlZikw3LewHKAuSmH43PwtF8dVGbdPE8aa2IMKRtI80BogQP9raq7T32nsFedNiXnfadhrBceUGY/Lx/wlMQk/1)

### Other comments
If this is the intended functionality, I think there should be a way to disable/solve it.

**Comment by MatthewAry** [comment]
I believe this bug is fixed. @simionato-mobisec Can you confirm? 

<img width="749" alt="Image" src="https://github.com/user-attachments/assets/c2bcd509-bc6b-4a6f-81c3-270e315098c9" />

I think this issue can be closed but I want @simionato-mobisec to confirm for me, hopefully soon.

**Comment by simionato-mobisec** [comment]
> I believe this bug is fixed. [@simionato-mobisec](https://github.com/simionato-mobisec) Can you confirm?
> <img alt="Image" width="749" src="https://private-user-images.githubusercontent.com/157217/405068867-c2bcd509-bc6b-4a6f-81c3-270e315098c9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mzc0NTIxMTYsIm5iZiI6MTczNzQ1MTgxNiwicGF0aCI6Ii8xNTcyMTcvNDA1MDY4ODY3LWMyYmNkNTA5LWJjNmItNGE2Zi04MWMzLTI3MGUzMTUwOThjOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMTIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDEyMVQwOTMwMTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jYzdjZDMwZDdiNTdjNmI0YjhkNzI0Mzc0NDAxZDc4MDBkYmU4Nzk0OWYyODVkYTkwZTA5NWY3OGY1MTg3MDA5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.7ZeJvd87GK2GKs3MYJITGhSDJl1FMKGfMIlQIuarPkY">
> 
> I think this issue can be closed but I want [@simionato-mobisec](https://github.com/simionato-mobisec) to confirm for me, hopefully soon.

IMHO is not fixed. `bg-color` applied to plain inputs should be ignored. **Why is it important?** When using global customization to set a `bg-color` to inputs, then I have to manually remove it from plain ones

**Comment by J-Sek** [comment]
(Devil advocate) assuming we adopt the requested change. When I have my unstyled/plain input and wish to change the background I am now forced to drop to CSS because `bg-*` class applies background to the `v-messages` ([demo](https://play.vuetifyjs.com/#eNqVU9tu2zAM/RVBe8gGxNaKrMMQpEW3byj6Mu1BkWlHm26QZK9FkH8fJTuNkw5o+2JL5CEPyUP93NMYJBt6SKp9qn9HuqbKeBcS2RMZQCR4GH3kQNrgDFlM2AW33MJjgUpnYyKTg9ycB37cc0tI2oGBNSlnQhpoRa/T/WhcaNXt0mI5+hjL/0O5Tbj4HPjwI9l713X6lGs0zq6ESC0ixixkH5Mzx8THpMd//h4+cUuXZQbfva+xBRzAJoHxGju4zbDNUAnvSUxPGm443Qr5pwuut00lnXZhTT5IKTkt2ILGaSShLITJVIwJHlPVKtDNqUwfwAPmURbBlcI4zG8aVRnRWZwcpyfsthvpEBGgmXsGEZSwCR1Ys7In1+2GzXlfq6YMLTfYVRcM76nzndVk4/m8sgXnjecNm+mAIo17iaQe99RZFKpIzidH5PR5CThFJfOd011KPq4Zk43FsAa0GkJtITHrDbtDGAu9TcpA1Thzt6qv68+V0H4n6hVrVExzdw3RVNvg/kYImIzTaZ8KXd71N1BOSGT6Wl9NFJOt0mIbM8eL3AwJB5x9QBkgQHhraxdh/2vvAvKixfJS8KGgBIclzQmuvqAYq/pbfU2XrdARzt/PaPv1D++JawY=)).

My initial advice would be to have an alias for plain input `{ VPlainTextField: { bgColor: 'transparent' } }`. I understand though it would need to be repeated for every form input based on VTextField.

**Comment by johnleider** [comment]
My suggestion would be to create an [aliasing](https://vuetifyjs.com/en/features/aliasing/#usage) component for the *variant="plain"* inputs. Then you can assign defaults specifically to it and not clash with all of the other inputs which you want the background color to be set.

There is nothing that states that the **plain** variant removes the background color. It removes padding/margin only. Thank you for your contribution and interest in improving Vuetify! Make sure to join us in the [Discord community](https://community.vuetifyjs.com).
