### ISSUE TITLE
[Bug Report][3.7.1] v-treeview class="v-list-group--id-[object Object]" when  return-object true

### ISSUE THREAD

**Issue by digitalniweb** [vuetifyjs/vuetify#20477]
### Environment
**Vuetify Version:** 3.7.1
**Vue Version:** 3.5.5
**Browsers:** Firefox 130.0
**OS:** Windows 10

### Steps to reproduce
add return-object to treeview with items with children.

### Expected Behavior
not getting v-list-group--id-[object Object] . Maybe getting id 'v-list-group--1' of the parent or nothing, just 'v-list-group' or 'v-list-group--treeview'

### Actual Behavior
getting v-list-group--id-[object Object]

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNplj91ugzAMhV/lKDdsUjvUXkZ00p6jcMFSV8sUQpQYdoF494UE2E9vYvvE/o59nUTwqnxz7mUcSEhRMXXOtEyvtQWq8dg6l9JUqN5yqy35VUoie6JR0xekjsPhUosUawFPPHh77N8/STHKjVP+By1K9qnKX/6xDMprxwgRlNfQnes9Y4rsO2bcfd+hiKsXSzsQuYGR/HFZep6u2XTaFtY3idNhq1izIYkiRZyK/UN9aHPzZCVWwB/IBjrv/Y+w8w8MmPe8WbOsNM/LzfnKeJ+YD3YwJj3NN7zhfMU=)

**Comment by KaelWD** [comment]
@johnleider that broke open-all (please run tests), and `item.raw` can be anything - `id` most likely does not exist.

**Comment by yuwu9145** [comment]
It should be fixed in VListGroup: https://github.com/vuetifyjs/vuetify/pull/20595

**Comment by johnleider** [comment]
> It should be fixed in VListGroup: [#20595](https://github.com/vuetifyjs/vuetify/pull/20595)

I'm still seeing it as this:

![Image](https://github.com/user-attachments/assets/0aad9241-71aa-4ba9-a5fd-11a5dbb2e860)

Do I need to do anything specific to check?

**Comment by yuwu9145** [comment]
> I'm still seeing it as this:

Need to apply `item-value` to VTreeview

```vue
<template>
  <v-app>
    <v-container>
      <v-treeview :items="items" item-value="id" return-object />
    </v-container>
  </v-app>
</template>

<script setup>
  import { ref } from 'vue'

  const items = ref([
    {
      id: 1,
      title: 'title 1',
      children: [
        {
          id: 2,
          title: 'title 2',
        },
      ],
    },
  ])
</script>


```

**Comment by kulkhareFC** [comment]
When is this fix going to be released?
