### ISSUE TITLE
[Bug Report] Data Table doesn't work if :headers isn't specified although :hide-headers is set to True

### ISSUE THREAD

**Issue by lkrazy** [vuetifyjs/vuetify#2585]
### Versions and Environment
**Vuetify:** 0.17.2
**Vue:** 2.5.7
**Browsers:** Chrome 62.0.3202.94
**OS:** Windows 7

### Steps to reproduce
1. Click on **Add More Data** button to load more data to the table
2. Check the **Data Table 2** you will see the problem

### Expected Behavior
Data should be presented on **Data Table 2**

### Actual Behavior
The table presents that ***No matching records found*** although the pagination work normally

### Reproduction Link
[https://codepen.io/lkrazy/pen/WXzNZQ](https://codepen.io/lkrazy/pen/WXzNZQ)

**Comment by jacekkarczmarczyk** [comment]
I've added https://github.com/vuetifyjs/vuetify/pull/2590 that blocks filtering if the search is empty, so in that case this issue should be solved, but how do you expect to filter data if you don't know which prop is storing the item's value? Normally the name of the prop is defined in the headers.

**Comment by lkrazy** [comment]
I'm not sure this will fix the issue totally. If i tried to enter the search text which matches several items, the table still shown ***no matching records found***. I think the problem is that filter based on headers.

**Comment by jacekkarczmarczyk** [comment]
Did you read my comment? "but how do you expect to filter data if you don't know which prop is storing the item's value? Normally the name of the prop is defined in the headers."

**Comment by lkrazy** [comment]
I'm sorry for misunderstanding. I think the filter function should work without headers (similar to v0.16.9) because the headers props is not required.

**Comment by jacekkarczmarczyk** [comment]
0.16.9 search all items' properties, personally i'm not sure if this is the good approach, maybe other team members have their opinion on that. At the moment you can workaround it by providing your own filter function (`customFilter` prop)

**Comment by lkrazy** [comment]
Thank you for your information.
How do you think if we keep current behavior but when headers is not specified, the it should search all item's properties?

**Comment by nekosaur** [comment]
I think this is enough of a niche use case that providing a custom filter would be the solution.
