### ISSUE TITLE
[Bug Report] Issue when loading dynamic content to v-expansion-panel-content 

### ISSUE THREAD

**Issue by YonathanB** [vuetifyjs/vuetify#3095]
### Versions and Environment
**Vuetify:** 0.16.6
**Vue:** 2.5.2
**Browsers:** Chrome 63.0.3239.132
**OS:** Windows 10

### Steps to reproduce
v-for on expansion-panel-content.
Click on item to open content.
On click an ajax call is made to load data inside

### Expected Behavior
I would like to load data each time I click on header, then show the data (when it is loaded) into the v-expansion-panel-content.

### Actual Behavior

It's not always working.
If user open the accordion before data is loaded, it wont be updated once data comes from server.

### Reproduction Link
[https://jsfiddle.net/yvbenitah/ag63f9fm/](https://jsfiddle.net/yvbenitah/ag63f9fm/)

**Comment by johnleider** [comment]
This was fixed in 0.17 branch. It is recommended that you upgrade as the only branch that will be maintained post v1.0 launch is 0.17.

**Comment by brysem** [comment]
I am still experiencing this exact same issue.

Vuetify: 1.0.18
Vue: 2.5.16
Browsers: Chrome 66.0.3359.181
OS: macOS High Siera (10.13.3)

```
<v-expansion-panel-content v-for="(topic, topicIndex) in area.children" :key="topicIndex">
    <div slot="header" @click="fetchSubjects(topic)">
        {{ topic.name }}
        <div @click="editTopic" class="edit action"><v-icon>edit</v-icon></div>
        <div class="delete action"><v-icon>delete</v-icon></div>
    </div>
</v-expansion-panel-content>
```

**Comment by YuanTian1991** [comment]
Hello:

I have the same problem, the axios fetched data are not updated on the component inside v-expansion-panel-content. Do you have any solution now?
