### ISSUE TITLE
[Bug Report] Fab buttons stay highlighted after being clicked

### ISSUE THREAD

**Issue by AlexSHoffman** [vuetifyjs/vuetify#3125]
### Versions and Environment
**Vuetify:** 0.17.6
**Vue:** 2.5.13
**Browsers:** Chrome 63.0.3239.132
**OS:** Windows 10

### Steps to reproduce
- Click the fab button on the reproduction page

- Notice how it stays highlighted after the click until you click somewhere else

### Expected Behavior
To not stay highlighted after a click

### Actual Behavior
Stays highlighted after a click

### Reproduction Link
[https://codepen.io/anon/pen/mXbjeq](https://codepen.io/anon/pen/mXbjeq)

**Comment by johnleider** [comment]
I know that in the past I added this for Material Design spec, but it may be within the context of a `v-speed-dial`. @vuetifyjs/dev-team thoughts?

**Comment by badders** [comment]
Note that this is also happening with both App Bars and Toolbars in the 2.0 beta series (currently using beta8 and still seeing this behaviour), and any v-btn in general

**Comment by curio77** [comment]
Still happening with `v-app-bar`'s `v-app-bar-nav-icon` in v2.0.1, for example.

**Comment by badders** [comment]
Possibly something being set on the css for :focus as buttons are remaining focused after click?

**Comment by leosia** [comment]
I have the same problem in v2.0.14. I managed to fix it by adding class to all my buttons.
`    .btn-fix:focus::before {
        opacity: 0 !important;
    }
`

**Comment by 185driver** [comment]
I would like to gently suggest that this issue be closed as `won't fix`. Some thoughts:

1. I too am a fan of icon-based buttons losing their focus after being clicked, but as far as I can tell, they're supposed to stay focused until blurred by some other element click. I imagine one reason is so that a user using a keyboard can see the tab progression in the browser.
2. [Google's md2 FAB docs](https://material.io/components/buttons-floating-action-button/#) seem to indicate that a clicked fab should retain focus, which can be observed in the interactive demo. If this premise is accepted as true, then the "real" bug may be that `<v-button icon>` **doesn't** retain focus after being clicked. Yikes.
3. On mobile, of course, the situation changes somewhat. If this codepen is run on a touch-enabled device, even the icon button retains a highlighted state, but that's because hover is being applied to button elements, and touch-enabled devices don't have hover state (there's no pointer). There are several possible fixes on mobile for the hover issue, but my preferred solution is to use the [remove-hover](https://www.npmjs.com/package/remove-hover) npm package. My point, however, is that hover is a separate (yet real) issue from element focus and sometimes people don't take them both into account on mobile.

Because this focus (and hover) issue is likely noticed by quite a few people, it might be good to either remove focus from all `v-btn`'s on click, or embrace the md2 norm fully and add something to the docs to help people understand the reasons why.

Here's a v2 version codepen of the submitted bug for reference, if needed:
https://codepen.io/185driver/pen/bGGBqgN

**Comment by johnleider** [comment]
This was resolved with the addition of the **retain-focus-on-click** property.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Comment by sebastianhaberey** [comment]
I have the same issue as OP and **retain-focus-on-click** doesn't seem to solve it. I don't see any effect using this parameter. The [workaround](https://github.com/vuetifyjs/vuetify/issues/3125#issuecomment-527843283) provided by @leosia works for me.

vue 2.6.11 / vuetify 2.2.21

**Comment by jpcarreira** [comment]
I can also confirm that **retain-focus-on-click** doesn't solve it, I've also fixed it with @leosia's class.

**Comment by runlong-yao** [comment]
Because **retain-focus-on-click** just fix the focus state,I guess.
But v-btn has hover css style,so **retain-focus-on-clic**k can not fix the bug.
So at this time, the best way is to add class for v-btn component

**Comment by nancologist** [comment]
> I have the same problem in v2.0.14. I managed to fix it by adding class to all my buttons.
> ` .btn-fix:focus::before { opacity: 0 !important; }`

Thx!! but it removed for me also the hover effect, so i had to
``.btn-fix:hover::before { opacity: 0.08 !important; }``

**Comment by bahablgn** [comment]
Adding these classes solved my problem thanks a lot.

.btn-fix:focus::before { opacity: 0 !important; }

.btn-fix:hover::before { opacity: 0.08 !important; }
