### ISSUE TITLE
[Feature Request] v-tabs Vertical option

### ISSUE THREAD

**Issue by AGPDev** [vuetifyjs/vuetify#3971]
### Problem to solve
i need use other vue plugin to create vertical tabs in complex projects 

### Proposed solution
implement option to use

**Comment by nekosaur** [comment]
Please provide more information about this feature request. Do you have an example of what you want to achieve? What would the proposed new markup look like?

**Comment by AGPDev** [comment]
<a href="https://i.imgur.com/Vv6QJxm.png">
  <img src="https://imgur.com/Vv6QJxml.png" />
</a>

I make this using v-list, v-card and CSS

**Comment by Blaconix** [comment]
I recently stumbled with a case where vertical tabs would be really beneficial. If it's not implemented soon, I was thinking about having a list change the v-model of a container.

Vertical tabs would be a great addition, though!

**Comment by ArturGrigio** [comment]
We had a similar use case, ended up using the `v-stepper` with `:vertical=true` and hiding the numbers in front of the steps.

It ended up looking like this:
![screen-shot-2018-06-29-at-3 52 56-pm](https://user-images.githubusercontent.com/6424589/42117999-e2f299bc-7bb4-11e8-80cb-e13a13248d76.jpg)

in this scenario, the `tabs` are the `steps` (*Employee Detail*, ..., ..., *History*)
and the `tab item` is the `stepper content`

**Comment by jacekkarczmarczyk** [comment]
I've created a component for my personal use: https://gist.github.com/jacekkarczmarczyk/eca6015c176e85ea78706e63383bbe5c

Usage: 
```vue
        <vertical-tabs v-model="tab" :items="['foo', 'bar', 'baz', 'foo bar', 'foo baz', 'bar baz', 'foo bar baz', 'lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum']"></vertical-tabs>

        <vertical-tabs vertical-text height="300" v-model="tab" :items="['foo', 'bar', 'baz']"></vertical-tabs>
```

It doesn't support router nor many tabs props (like show-arrows, icons, etc), first version (with horizontal text) has fixed width 200px, but maybe some people will find it useful in their projects

![image](https://user-images.githubusercontent.com/15625235/43684784-effedd5a-98a6-11e8-9163-e281b9874fa0.png)

**Comment by tjb1187** [comment]
Artur would you be kind enough to share some code for how you got your verticle tabs working? I'm trying to replicate but having a few issues? Thanks

**Comment by johnleider** [comment]
![vertical-tabs](https://user-images.githubusercontent.com/9064066/53537928-46170380-3ad1-11e9-83d7-89ffacda1f51.gif)

**Comment by johnleider** [comment]
Resolved in f22d754

**Comment by nima-rnd** [comment]
using <v-tabs vertical> still showing horizontal , i updated vuetify still having this issue

**Comment by MajesticPotatoe** [comment]
This is in 2.0 alpha build.
We kindly ask users to not comment on closed/resolved issues. If you believe that this issue has not been correctly resolved, please create a new [issue](https://issues.vuetifyjs.com) showing the regression or reach out to us in our [Discord community](https://community.vuetifyjs.com).

Thank you for your contribution and interest in improving Vuetify.
