### ISSUE TITLE
[Bug Report] Selected options are removed when options are updated even when options are available in model property

### ISSUE THREAD

**Issue by akki-jat** [vuetifyjs/vuetify#4000]
### Versions and Environment
**Vuetify:** 1.0.16
**Vue:** 2.5.11
**Browsers:** Chrome 66.0.3359.139
**OS:** Windows 7

### Steps to reproduce
Click on update button.
Then see in model there is but selection is removed from v-select

### Expected Behavior
Option should not removed from selection

### Actual Behavior
It is removed from selection

### Reproduction Link
[https://codepen.io/akki-jat/pen/yjPXPL](https://codepen.io/akki-jat/pen/yjPXPL)

**Comment by KaelWD** [comment]
That behaviour is intentional, although it should be removed from the model too iirc.

**Comment by akki-jat** [comment]
Hi @KaelWD, I want behavior like, if i remove from list after selecting it should be displayed as selected.
Is that possible?

**Comment by KaelWD** [comment]
If you use `cache-items` then yes, although it will still be visible in the menu. I don't really know what your use-case is for this though.

**Comment by akki-jat** [comment]
@KaelWD thanks for your answer, I can use cache-items but if it would be good if removed item is not visible in list.

**Comment by akki-jat** [comment]
And if you want reference of this use-case, you can check libraries like vue-multiselect or element-ui's select component.

**Comment by KaelWD** [comment]
I don't think that's good behavior. If the item is removed from the list but still selected then there will be no way to unselect it. The `el-select` seems similar to our `<v-select tags>` however, which does appear to have the behaviour you want.

**Comment by akki-jat** [comment]
@KaelWD ok, thanks for answer.

**Comment by akki-jat** [comment]
@KaelWD But if i make v-select autocomplete then there is problem.
It will allow user to create tag.

**Comment by akki-jat** [comment]
Hi @KaelWD , can you check changes I made related to this issue.
And I am new to contributing, if there is anything I can improve you can tell me

**Comment by johnleider** [comment]
You cannot have a selection that is not present in the available options. The fact that it leaves the model is completely fine as you can provide whatever value you want to the input.  I see that you provided an example of another framework working as you want, but I'd argue to say that it is invalid and not what you would expect from a regular select, so it will not be here.

**Comment by akki-jat** [comment]
Hi @johnleider, I also agree with you. But in my use-case I want this behaviour, ok let me tell you how I am using v-select.
I have four v-select.
1.) Destinations
2.) Sailing Dates
3.) Sailing Duration
4.) Departure Ports

And all four v-select's options are dependent on each other, means if I select destination it will update all other three v-select's options.

So, if user selected 3 destination then it will update all other three and after that if user selects from available Sailing Dates it will also update destinations then user's selection will disappear from v-select.

I don't know about you, but if I am the user and my selection is removed automatically without touching it, I will be pissed.

**Comment by nekosaur** [comment]
This could be solved by for example adding the already selected option to the updated values and notifying the user that it is no longer valid, for example displaying it as disabled or with red text.

**Comment by akki-jat** [comment]
@nekosaur yup I can update the list, but then it will change the position of selected value and for displaying it as disabled is not appropriate in my case because I want the user to have with option to deselect it even if it is not in the list because I am maintain the another array for that.

What do you say?

**Comment by KaelWD** [comment]
I can see the argument for both of these, and the current behaviour is technically buggy too because it removes the value from the input but doesn't update the model. I don't like adding yet another prop to the component though, so we have to decide if it should instead be the default behaviour to show the model even if it's not in items.

**Comment by johnleider** [comment]
I would say this is out of the hands of the component. If you are mutating the items to dynamically remove items, you should dynamically update the model as well.

**Comment by KaelWD** [comment]
We've decided to consider this after someone on discord posted a similar problem: https://codepen.io/anon/pen/ERmeZZ

**Comment by KaelWD** [comment]
Another use-case for this: 
![image](https://user-images.githubusercontent.com/16421948/42302902-414a8c30-8061-11e8-9a10-1f9089ee0988.png)

**Comment by kanteankit** [comment]
Is there a workaround, while this issue gets resolved?
I am using `v-autocomplete` to search for a list of names asynchronously using an API call. I show 5 names initially. When user searches for a name, API call is made to fetch search results. I am using `cache-items` prop.
Now, my requirement is as follows:
When the `v-autocomplete` loads, I want to provide it with some pre-selected names. The problem I am running into is that since some of the pre-selected names are not available in the initial list of names, they never show up in the selection.
So, for example, There are 20 names on the server(`name1`,`name2`,.....`name20`) and the initial list only has 5 names(`name1` to `name5`). Now, if I want `name7` to be already selected, it is not possible right now because it is not present in the list.

**Comment by BigsonLvrocha** [comment]
> **Is there a workaround, while we wait for this issue to get resolved?**
> I am using `v-autocomplete` to search for a list of names asynchronously using an API call. I show 5 names initially. When user searches for a name, API call is made to fetch search results. I am using `cache-items` prop.
> 
> Now, my requirement is as follows:
> When the `v-autocomplete` loads, I want to provide it with some pre-selected names. The problem I am running into is that since some of the pre-selected names are not available in the initial list of names, they never show up in the selection.
> So, for example, There are 20 names on the server(`name1`,`name2`,.....`name20`) and the initial list only has 5 names(`name1` to `name5`). Now, if I want `name7` to be already selected, it is not possible right now because it is not present in the list.

The workaround I found out is to manually add set model's value using searchInput's setter, triggering a server query, here is a working codepen, I usually use Vuex and lodash to throttle server requests
https://codepen.io/BigsonLvrocha/pen/oOqqLZ

**Comment by BigsonLvrocha** [comment]
I needed to do an autocomplete with multiple selection and server side rendered list (the user able to select one or more names, which have too many options), `cache-items` would not be an option since they wanted multiple field filtering (the text can match the name or the login name), so I used no-filter prop to give this responsibility solely to the server.
The workaround I made for this case is to use `prepend-item` slot to show the selected items inside my own value variable. I show them as a list with a checkbox icon in the tile action to indicate that it is selected and a divider for aesthetics. 
I tried to use `selection` prop to show the number of selected items only at the first item, but I ran into this problem, which was making the text disappear when the user tried to filter for another result, so I am using `prepend-inner` slot for it, with a span wrapped in a slide-x transition for smoothness. 
I know this is an edgy use case, but still a use case for what the component proposes

**Comment by kanteankit** [comment]
@KaelWD Does this issue have an open PR? The label `has PR` was attached a long time ago and since then nothing has happened.

**Comment by akki-jat** [comment]
@kanteankit It had open PR but library author closed PR with comment **Unfortunately this is not functionality that we are looking to implement at this time.**

PR Link: https://github.com/vuetifyjs/vuetify/pull/4028

**Comment by kanteankit** [comment]
@johnleider Can we re-open it and see if this can get fixed?

**Comment by joaoeudes7** [comment]
@akki-jat That is the answer for most PR, I do not understand why bug fixing is not the functionality you intend to implement, would you prefer something with bugs? it is?

**Comment by joaoeudes7** [comment]
@akki-jat  That is the answer for most PR, I do not understand why bug fixing is not the functionality you intend to implement. Prefer components with bugs? it is?

**Comment by NickMSW** [comment]
Is there an update on this? It seems there is a fair amount of traffic linked to this issue and should be pushed up the stack.

**Comment by impowski** [comment]
I'm waiting for an update too

**Comment by johnleider** [comment]
This has since been resolved with the property **cache-items**.

https://codepen.io/johnjleider/pen/ZEeVrXr?editors=1010

Closing this as resolved.

If you have any questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Comment by BigsonLvrocha** [comment]
With cache-items, the item still shows up when unselected which is unwanted in a server side rendered options scenario. One way I found out was to use computed property: https://codepen.io/BigsonLvrocha/pen/abJPYVz

**Comment by cherrybar** [comment]
Probably it could be helpful for someone, I tried workaround suggested above (https://codepen.io/BigsonLvrocha/pen/abJPYVz?editors=1010), but i need to use server side search by many attributes, and if i simply add `no-filter` prop then selected options would still be displayed in list, regardless of whether they meet search condition or not.
So i added `filter` prop with following value:
```
    filter(item) {
      return this.searchResults.some((itemFromServer) => itemFromServer.id === item.id)
    },
```
Here i just check if item exist in array received from the server. And if it exists, then it will be displayed in the list. If it not, then it won't be displayed, but it still will be presented in VAutocomplete items, thus selected items remain visible.
