### ISSUE TITLE
[Bug Report] v-text-field with "prefix" and "single-line"

### ISSUE THREAD

**Issue by Tiagosophy** [vuetifyjs/vuetify#4268]
### Versions and Environment
**Vuetify:** 1.0.19
**Vue:** 2.5.16
**Browsers:** Chrome 66.0.3359.181
**OS:** Windows 10

### Steps to reproduce
Focus on the text field

### Expected Behavior
Do not move the placeholder over the prefix

### Actual Behavior
The placeholder get over the prefix

### Reproduction Link
[https://codepen.io/tiagoxavi/pen/eKveem](https://codepen.io/tiagoxavi/pen/eKveem)

**Comment by jacekkarczmarczyk** [comment]
Fixed in 1.1
https://codepen.io/anon/pen/Qxpayw

**Comment by dh3wr** [comment]
For long prefixes not fixed:
https://codepen.io/dh3wr/pen/VEJQNv

Vuetify: 1.3.4
Vue: 2.5.17
Browsers: Chrome 69.0.3497.100
OS: Windows 7
