### ISSUE TITLE
[Bug Report] tabs have extra margins when in a toolbar

### ISSUE THREAD

**Issue by KaelWD** [vuetifyjs/vuetify#4420]
### Versions and Environment
**Vuetify:** 1.1.0-rc.3
**Vue:** 2.5.16
**Browsers:** Chrome 67.0.3396.87
**OS:** Windows 10

### Steps to reproduce
Resize to ~1300px width

### Expected Behavior
As in 1.0, tabs should be right against the edge: https://codepen.io/anon/pen/qKLNoM?editors=1000

### Actual Behavior
There is an extra 24px margin on either side

### Reproduction Link
[https://codepen.io/anon/pen/yEGJEX?editors=1000](https://codepen.io/anon/pen/yEGJEX?editors=1000)

### Other comments
#4305 should be reverted, gutters were complex for a reason. 
This can't be easily fixed with negative margins. 

Mobile: 
![image](https://user-images.githubusercontent.com/16421948/42080001-99e04944-7bc4-11e8-951a-16ab0835567c.png)

Arrows visible:
![image](https://user-images.githubusercontent.com/16421948/42080104-dc68c5de-7bc4-11e8-9ec7-848dbee86a1f.png)

**Comment by peluprvi** [comment]
Between 1264px and 1377px it has an extra extra margin left. Both versions have this behavior.
The regression is the applied gutter which 1.0 doesn't have.

Version fixed codepens:
- 1.0.19: https://codepen.io/anon/pen/vrbRpV?editors=1100
- 1.1.1: https://codepen.io/anon/pen/oymqEd?editors=1100

Things to analise:
- #4305 fixes a lot of wrong alignments, including:
  - between buttons, icons, menus or tooltips
  - different buttons usage (icon, toolbar items, default buttons)
  - the title to the left
  - content gutter in all breakpoints
- The way it is today, the user can't remove the padding by using `px-0`, because the padding is at the content (same issue as #3936)
- (future) MD2 spec has an extra left margin if [scrollable tabs](https://material.io/design/components/tabs.html#scrollable-tabs)

**Comment by johnleider** [comment]
Fixed in f22d754

**Comment by gadelkareem** [comment]
I think this is still happening https://codepen.io/gadelkareem/pen/EqdWYY

**Comment by gadelkareem** [comment]
I think the 'v-tabs-bar--is-mobile' class is added on width between 940px and 1400px, something like that. Try changing width and keep your eye on the margin.

**Comment by arnovanoordt** [comment]
Same issue. Seems to switch at around 1100px.
Fixed it for now by adding to my css:
```
.v-tabs-bar.v-tabs-bar--is-mobile .v-tab {
    margin-left: 0px !important;
}
```

**Comment by VIXI0** [comment]
@arnovanoordt that work for me thank U. if they are not fixing this, at least they should put a property to.
