### ISSUE TITLE
Tab slider is not adjusted for dynamic tabs

### ISSUE THREAD

**Issue by MitchelLabonte** [vuetifyjs/vuetify#476]
### Steps to reproduce
- Add a _v-tabs_ components with three tabs
- In runtime, dynamically add a fourth tab to the component
- Click on the newly added tab

### Versions
Firefox 45.8.0
Vuetify 0.11.1

### What is expected ?
The tab slider should slide under the fourth tab.

### What is actually happening ?
The tab slider only slides for the first three tabs (the static tabs).
Note that a similar issue is happening if there are a lot of tabs on component creation and they are dynamically removed: the slider stays small when the tabs grow bigger.

### Reproduction Link
https://codepen.io/ElMitchL/pen/WjjaQW

**Comment by johnleider** [comment]
I'm actually encountering this as I build the new documentation. It'll be something that is addressed for 0.12.0

**Comment by arhont375** [comment]
It seems that this problem is still appear:
https://codepen.io/anon/pen/LjrNdy

Actually it not adjusted for deleted tabs to
