### ISSUE TITLE
[Bug Report] v-tabs-items does not display first item by default

### ISSUE THREAD

**Issue by blalan** [vuetifyjs/vuetify#5222]
### Versions and Environment
**Vuetify:** 1.3.0-alpha.1
**Last working version:** 1.2.6
**Vue:** 2.5.17
**Browsers:** Chrome 69.0.3497.100
**OS:** Windows 7

### Steps to reproduce
Open Codepen

### Expected Behavior
On load the first tabs is selected or the tab "active" via v-model. 

### Actual Behavior
page is blank

### Reproduction Link
[https://codepen.io/anon/pen/yReQvR?editors=1011](https://codepen.io/anon/pen/yReQvR?editors=1011)

**Comment by SuperGerb** [comment]
I think it's just an error in your sample code. Here's the fix: https://codepen.io/carterst/pen/oaLKqL?editors=1011. You had an unnecessary v-tab-items tag.

**Comment by blalan** [comment]
The v-tabs-items is quite necessary if you want to add touchless, which I do.

**Comment by johnleider** [comment]
fixed in bc6bd60a

**Comment by blalan** [comment]
This bug is still occurring in the beta... can we re-open this issue?
