### ISSUE TITLE
[Feature Request] v-combobox dropdown menu should disappear when a new item is created

### ISSUE THREAD

**Issue by joeczucha** [vuetifyjs/vuetify#5639]
### Problem to solve
I've had reports from users that they are "unable to add their own items to the list" when using a v-combobox.

Having investigated, they **are** actually able to use their own input. However, I think that the fact that the dropdown remains open is confusing them as it makes it look like their input hasn't been accepted.

It's not so bad when you're using tags:
https://monosnap.com/file/yhNBQZv9kguRNaNtdRV8vdxdoSdQFT

But when you're not, it's a bit unclear:
https://monosnap.com/file/QFHZAs11eunsfuI2BTtLq4kGmEWPXt

### Proposed solution
I think that hiding the dropdown when the user presses "enter" is probably sufficient to make this clearer. Otherwise, perhaps some kind of visual queue when they press enter?

**Comment by bviala** [comment]
@joeczucha You put two time the same link buddy 😬 

Totally agree with this problem, UX is very bad for non chip combobox.

Meanwhile you can force the menu to disappear using a ref:

https://www.reddit.com/r/vuetifyjs/comments/819h8u/how_to_close_a_multiple_autocomplete_vselect/

**Comment by joeczucha** [comment]
@bviala Good spot 👍 sorry about that, it had been a long day :) Fixed now.

Awesome - I'll have a play with that this afternoon, thanks for that!

**Comment by KaelWD** [comment]
@joeczucha It might be clearer if you remove the "No results matching" slot? The value will be saved when the input loses focus, you don't have to press enter.

**Comment by edwardsph** [comment]
@KaelWD I know this is quite old now but I think the issue still stands. You are right that it is clearer if you don't use the no-data slot but then I think the user does benefit from the hint this slot allows. It's such an obvious benefit that there is even this specific example in the docs: https://vuetifyjs.com/en/components/combobox/#no-data-with-chips. I tried closeOnContentClick but that didn't help. It is a shame that using this slot appears to lead to inconsistent behaviour. For now using a hint is the best we can do to guide the user.

**Comment by kairyou** [comment]
For temporary solution
```vue
<v-combobox ref="select" @change="hideMenu" .../>
```
```js
methods: {
    hideMenu () { this.$refs.select.blur() },
},
```
