### ISSUE TITLE
[Bug Report] Cannot set property 'touched' of undefined

### ISSUE THREAD

**Issue by tobiasdalhof** [vuetifyjs/vuetify#6477]
### Versions and Environment
**Vuetify:** 1.5.1
**Last working version:** 1.5.0
**Vue:** 2.6.6
**Browsers:** Chrome 71.0.3578.98
**OS:** Windows 10

### Steps to reproduce
Change route on btn click inside router-view

### Expected Behavior
No error

### Actual Behavior
Throws error "Uncaught TypeError: Cannot set property 'touched' of undefined"

### Reproduction Link
<a href="https://codepen.io/tobiasdalhof/pen/qgKJdz" target="_blank">https://codepen.io/tobiasdalhof/pen/qgKJdz</a>

**Comment by Choko256** [comment]
Same thing can be reproduced with the `v-autocomplete` component when clicking on one of the items in the generated list.

**Comment by MajesticPotatoe** [comment]
resolved with 0cd5671

**Comment by iyerusad** [comment]
Has this shipped? I see its merged but latest 1.5.1 appears to still have this issue (not sure when a merge makes it into a release for vuetify).

**Comment by Depender-Sethi** [comment]
@iyerusad I was facing the same issue on 1.5.1, fixed it by the following

node_modules/vuetify/lib/directives/ripple.js

Search for **'rippleHide' function** about line 150th line (First search)
add the conditional check for  **element._ripple**

```
if (element._ripple) {
      element._ripple.touched = false;
}
```

**Comment by iyerusad** [comment]
Yes thats what https://github.com/vuetifyjs/vuetify/commit/0cd56717b0b4334c78e8e99dc7bad6b7dc479d0b achieves, and it has been merged in. I am wondering if it has made it into package release.

**Comment by Depender-Sethi** [comment]
We are on the latest one, so I don't think so ¯\_(ツ)_/¯

**Comment by MajesticPotatoe** [comment]
this was merged after 1.5.1 as it appeared in 1.5.1, you will see it in the next build.

We kindly ask users to not comment on closed/resolved issues. If you believe that this issue has not been correctly resolved, please create a new [issue](https://issues.vuetifyjs.com) showing the regression or reach out to us in our [Discord community](https://community.vuetifyjs.com).

Thank you for your contribution and interest in improving Vuetify.
