### ISSUE TITLE
[Bug Report] v-calendar incompatible model value

### ISSUE THREAD

**Issue by Tamakiwan** [vuetifyjs/vuetify#6552]
### Versions and Environment
**Vuetify:** 1.5.2
**Vue:** 2.6.6
**Browsers:** Chrome 72.0.3626.109
**OS:** Mac OS 10.14.3

### Steps to reproduce
Click on any date on the calendar. The console displays the following message:

`Invalid prop: type check failed for prop 'value'. Expected String with value '[object Object]', got Object`

If you modified the start value before clicking on any day, you'll also see that the value is being reset.

### Expected Behavior
Emit the expected click event without the start value being reset.

### Actual Behavior
No event is emitted, and the start value resets.

### Reproduction Link
<a href="https://codepen.io/MarinaGranell/pen/mvogey?&editable=true&editors=101" target="_blank">https://codepen.io/MarinaGranell/pen/mvogey?&editable=true&editors=101</a>

**Comment by ShetlandJ** [comment]
Noticed this one too. Keen to use the calendar so am interested in seeing a fix

**Comment by farrance** [comment]
Same thing here. Is there a way to mute the issue for now?

**Comment by ClickerMonkey** [comment]
The fix was merged into master, so it should be out in the next 1.5.0 patch (I believe tomorrow?)

**Comment by tfprado** [comment]
Sorry to comment on a closed issue, but I am currently using vuetify@1.5.0 and I am still getting the exact same error on every browser. Has the fix been added to the patch?

**Comment by tesis** [comment]
@tfprado Having the same issue with vuetify@1.5.2, I upgraded to 1.5.9 and works fine
