### ISSUE TITLE
[Bug Report] VTabs pagination int rtl mode wont work properly

### ISSUE THREAD

**Issue by FunnyPhantom** [vuetifyjs/vuetify#6575]
### Versions and Environment
**Vuetify:** 1.5.2
**Vue:** 2.6.6
**Browsers:** Chrome 72.0.3626.109
**OS:** Windows 10

### Steps to reproduce
clone repository.
run `npm install`
run `npm run serve`

### Expected Behavior
when the `<v-tabs>` component is overflowed and when `$vuetify.rtl` option is set to `true`, the items shall be in their right place.

### Actual Behavior
the `<v-tab>` in `<v-tabs>` seem to be off and not to be in their right places when the `<v-tabs>` overflows, and pagination will show a big offset to the right.

### Reproduction Link
<a href="https://github.com/FunnyPhantom/vuetify-bug-report" target="_blank">https://github.com/FunnyPhantom/vuetify-bug-report</a>

**Comment by johnleider** [comment]
Fixed in f22d754

**Comment by nagwan** [comment]
the bug still there
i am using version 1.5.7
and when i set the body direction to rtl  i have to set the v-tabs direction to ltr to work properly otherwise it won`t

**Comment by DRoet** [comment]
it's fixed in `2.x`, which will enter beta at the end of the month

**Comment by nagwan** [comment]
aha, thanks
