### ISSUE TITLE
High CPU usage on documentation site

### ISSUE THREAD

**Issue by areading314** [vuetifyjs/vuetify#720]
### Steps to reproduce
* Go to API documentation page: https://vuetifyjs.com/vuetify/quick-start
* Watch CPU usage -- its still reasonable
* Click once on  the Components menu item on the left hand side to expand long list of components in sidebar
* CPU usage will spike while Components menu is open

### Versions

* Arch linux using Version 59.0.3071.86 (Official Build) (64-bit)

* NOTE: This did not happen in Firefox 53 

### What is expected ?

* Reasonable CPU usage

### Reproduction Link

https://vuetifyjs.com/vuetify/quick-start

EDIT: Clarification: Behavior observed in Google Chrome browser.

**Comment by johnleider** [comment]
There are a few things missing from this equation. Firstly, what are the specs of your computer? You say reasonable CPU usage, but don't define what your usage is. On my work computer I see the % go from ~4% to ~7% when opening that section, but that is irrelevant since this is not a slow computer.

Please understand that even though this ticket is following the guidelines for reporting, it gives absolutely no information that I could use to look into this situation.

**Comment by fenivana** [comment]
At "buttons" page ( https://vuetifyjs.com/components/buttons ), stay and do nothing, my CPU usage is around 7% (Surface Book, i5). This is unreasonable because the page isn't doing anything visually. I don't know whether there's some bug in the example codes, or in the components.

![image](https://user-images.githubusercontent.com/11750532/26943319-b452f84a-4cb7-11e7-8926-aff856de9350.png)

**Comment by johnleider** [comment]
Thank you, that is much more helpful.

**Comment by johnleider** [comment]
Looks like it is being caused by the data-table.

**Comment by johnleider** [comment]
This should be resolved with #727

**Comment by techntrails** [comment]
Performance issues are not resolved yet. Most of the component pages in the docs seem to have this issue. If I have a Chrome tab open with a Vuetify Datatable, my macbook battery only lasts ~25% the time in normally does

**Comment by nekosaur** [comment]
This fix has not yet been released. It will be available in 0.13

**Comment by techntrails** [comment]
@nekosaur I forgot to mention... I've tested this on the 0.13 and it's still not fixed, at least with the Datatable component. I've even tried disabling the linear progress bar

**Comment by nekosaur** [comment]
Are you sure you're running the dev build? If so, please create a new issue using the template and as much information as possible.

**Comment by techntrails** [comment]
Actually, I just did a quick test of the .13 release and didn't see the issue. Will check again when I have time to upgrade my code to use .13

**Comment by outluch** [comment]
Same problem on Macosx 10.13.2 / Safari 11.0.2. And webpack boilerplate causes 100% too. Only when Window is focused!
