### ISSUE TITLE
[Bug Report] Error message is shown after first keypress in dialog

### ISSUE THREAD

**Issue by jloewe** [vuetifyjs/vuetify#7294]
### Versions and Environment
**Vuetify:** 1.5.14
**Vue:** 2.6.10
**Browsers:** Chrome 74.0.3729.157
**OS:** Windows 10

### Steps to reproduce
1.  Open Dialog
2.  Type something in the textfield
3.  The error message is shown after the first keypress and immediately hidden again

### Expected Behavior
The error message only shown if there is an error

### Actual Behavior
It is shown after the first keypress and than immediately hidden again

### Reproduction Link

![Hvr1D9tyFT](https://user-images.githubusercontent.com/11992962/58369476-25f1b780-7efb-11e9-8a85-5214761fef93.gif)

<a href="https://codepen.io/jloewe/pen/qGYabw" target="_blank">https://codepen.io/jloewe/pen/qGYabw</a>

**Comment by KaelWD** [comment]
Possible duplicate of #4266

**Comment by johnleider** [comment]
This is resolved as of v2.

**Comment by jloewe** [comment]
@johnleider 

Hi, it looks like this bug still persists.

New v2.x Reproduction:
https://codepen.io/jloewe/pen/vYBJBPJ
