### ISSUE TITLE
[Bug Report] v-time-picker with `full-width` has a width of nearly zero

### ISSUE THREAD

**Issue by ascott18** [vuetifyjs/vuetify#9084]
### Environment
**Vuetify Version:** 2.0.18
**Vue Version:** 2.6.10
**Browsers:** Chrome 77.0.3865.90
**OS:** Windows 10

### Steps to reproduce
Click on one of the text fields

### Expected Behavior
Picker is usable when using `full-width` prop

### Actual Behavior
Picker is unusable
![image](https://user-images.githubusercontent.com/5017521/65539122-a5998e00-debd-11e9-97f7-d1029b5e567b.png)

The examples DO work when opened in Codepen.

### Reproduction Link
<a href="https://vuetifyjs.com/en/components/time-pickers#in-dialog-and-menu" target="_blank">https://vuetifyjs.com/en/components/time-pickers#in-dialog-and-menu</a>

**Comment by MajesticPotatoe** [comment]
caused by 450f013
will investigate tonight.

**Comment by MajesticPotatoe** [comment]
resolved in 2.0.19 and 2.1.0-beta.x

**Comment by arntdr** [comment]
I still see this issue on 2.0.19 and 2.1.1. The issue aslo appears in the [docs](https://vuetifyjs.com/en/components/time-pickers#playground)

![image](https://user-images.githubusercontent.com/35137653/66314208-fd9bb000-e913-11e9-8c8b-435d0f319627.png)

**Comment by MajesticPotatoe** [comment]
Issue seems to still exist. reopening.

**Comment by arntdr** [comment]
With Vuetify 2.1.4 this is resolved in my app. The [picker in dialog](https://vuetifyjs.com/en/components/time-pickers#in-dialog-and-menu) example in the docs also works, but the [playground](https://vuetifyjs.com/en/components/time-pickers#playground) has some strange behavior, where it starts faily small, and grows on change, but never gets large.

**Comment by MajesticPotatoe** [comment]
@arntdr different issue but also would disregard for now as all playgrounds are in the process of being updated (just a slow process as there are so many of them). Thank you for the validation of it being fixed though.
