### ISSUE TITLE
[Bug Report] V-sheet without tile prop hasn`t a border-radius

### ISSUE THREAD

**Issue by CitRUSprod** [vuetifyjs/vuetify#9329]
### Environment
**Vuetify Version:** 2.1.3
**Vue Version:** 2.6.10
**Browsers:** Chrome 74.0.3729.169
**OS:** Windows 10

### Steps to reproduce
Just see a link

### Expected Behavior
V-sheet without tile prop has a border-radius

### Actual Behavior
V-sheet without tile prop hasn`t a border-radius

### Reproduction Link
<a href="https://codepen.io/imCitRUS/pen/abbdbER" target="_blank">https://codepen.io/imCitRUS/pen/abbdbER</a>

**Comment by johnleider** [comment]
This is resolved as of the latest patch on v2.1: https://codepen.io/johnjleider/pen/dyPmLro

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).

**Comment by jblachly** [comment]
Regression? in 2.3.0 (still present in 2.3.5), now including the "tile" property does not remove the border radius.

Using same codepen link from @johnleider (https://codepen.io/johnjleider/pen/dyPmLro), change vuetify in settings to: `https://cdnjs.cloudflare.com/ajax/libs/vuetify/2.3.0/vuetify.min.js` and both sheets have border-radius.

Strangely on the documentation page for VSheet, there is the opposite problem: the example shows **always a tile**, no matter whether the boolean switch is flipped:

[https://codepen.io/pen/?&editable=true&editors=111=https%3A%2F%2Fvuetifyjs.com%2Fen%2Fcomponents%2Fsheets%2F](https://codepen.io/pen/?&editable=true&editors=111=https%3A%2F%2Fvuetifyjs.com%2Fen%2Fcomponents%2Fsheets%2F)
